### ISSUE TITLE
Cannot GET /multilaterals

### ISSUE THREAD

**Issue by dw8547** [devinit/datahub#144]
Link affected: http://data.devinit.org/multilaterals

Can access when going through http://data.devinit.org/, not otherwise.

![screenshot from 2017-11-10 12 37 42](https://user-images.githubusercontent.com/10259585/32658933-3114c2ac-c614-11e7-9744-4cb39d9df136.png)

**Comment by epicallan** [comment]
@dw8547 Thanks for reporting this. I have corrected it.

**Comment by dw8547** [comment]
Cannot GET /pdf/multilaterals/EU.pdf, for example. See screenshot below:
![screenshot from 2017-12-14 10 50 47](https://user-images.githubusercontent.com/10259585/33988642-e0066622-e0bc-11e7-8ca8-bce8a5095a82.png)

**Comment by aleku399** [comment]
I am going to look into it.

**Comment by dw8547** [comment]
@aleku399, have you been able to resolve?

**Comment by epicallan** [comment]
This was fixed a long time ago.
