### ISSUE TITLE
Cannot GET /pdf/[date]/[country_name].pdf

### ISSUE THREAD

**Issue by dw8547** [devinit/datahub#146]
Link affected: http://data.devinit.org/country/country_name .

There are a number of countries that should not have the "Download and Print" option.
@Duncan-Knox has the full list of countries for which this is the case.

For example:
![screenshot from 2017-12-05 11 40 44](https://user-images.githubusercontent.com/10259585/33605362-55718c42-d9b1-11e7-9f5b-c2eb3f9be0fb.png)

https://github.com/devinit/ddw-data/issues/252 might help too.

**Comment by epicallan** [comment]
Hi @Duncan-Knox can you pass me the list of countries we should exclude for pdf downloads

**Comment by Duncan-Knox** [comment]
Hi @epicallan, these are non-recipient countries which don't currently have PDFs, **however as discussed we are developing non-DAC donor PDFs for them**. Currently they have PDF links but there is no content to show for them so it leads to a "cannot get" page. The countries are:

Bulgaria
Croatia
Cyprus
Estonia
Israel
Kuwait  
Latvia
Liechtenstein
Lithuania
Malta
Romania
Russia
Saudi Arabia
Chinese Taipei (Taiwan)
United Arab Emirates
Qatar

On another note - **Hungary** - is one of these, however it has become a DAC donor now - so this ought to be reflected in the next update.

Duncan

**Comment by dw8547** [comment]
@epicallan re:

> On another note - Hungary - is one of these, however it has become a DAC donor now - so this ought to be reflected in the next update.

Please supress download option for now. It will need to be enabled again after the Janury update.
