### ISSUE TITLE
International Official Finance maps tab updates

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub#153]

**Comment by Duncan-Knox** [comment]
Hi @epicallan and @dw8547 Review of staging: series Gross ODA received (in-oda-gross) under International Official Finance on the Global Picture, below:

**Visual/functionality:** 

High priority:

- [ ] Toggle slider is out of line for 2000, e.g.: 
![image](https://user-images.githubusercontent.com/13347058/35680488-6f86c164-0752-11e8-834c-e0b7e90a3e96.png)


Low priority

- [ ]	Functionality : if slider is moved quickly colours half appear  on some countries momentarily. E.g. DRC.
![image](https://user-images.githubusercontent.com/13347058/35680818-4ddd6e86-0753-11e8-8dd8-d11855b5b108.png)
- [ ] Click and drag on slider is not always fully responsive.
- [ ] If Slider is moved relatively quickly, the changes on the map can lag, not sure if this is a staging thing

**Data/notes/other content**

Low priority (let me know if I can help on these by editing the info in any relevant Github page)

- [ ] Can we add a notes heading to the i. This would be located under the source heading. This would state: **notes**: ODA shown is provided by DAC donors and multilateral organisations reporting to the OECD DAC; recipients shown include those on the historical and current DAC lists of ODA recipients.
- [ ] Can the note on the left hand side please be edited to state: "Gross official development assistance (ODA) includes monetary transfers (e.g. grants and loans to governments and for project-type interventions), non-monetary transfers (e.g. food aid, technical cooperation) and ODA that resulted in no additional transfer of resources (e.g. debt relief). Data is in constant 2015 prices"


Let me know if any questions Allan.
Checking documents and spreadsheet available on request.

**Comment by epicallan** [comment]
Thanks @Duncan-Knox Will look into these some time tomorrow and Monday.

**Comment by epicallan** [comment]
@Duncan-Knox Notes / descriptions can be edited from here https://github.com/devinit/datahub-cms/blob/master/global-picture/concept.csv

**Comment by dw8547** [comment]
@Duncan-Knox please let me know if you'd like me to show you how to do that.

**Comment by Duncan-Knox** [comment]
Thanks for linking the notes/descriptions @epicallan. 

Sure, please @dw8547 this would be helpful.

**Comment by dw8547** [comment]
Let me know when you have time @Duncan-Knox and we'll go over that, unless you already know it but don't know that you do know!

**Comment by Duncan-Knox** [comment]
Hi @epicallan. Review of staging: series Net ODA provided by OECD DAC members % of GNI  (oda-percent-gni) under International Official Finance on the Global Picture, below:

- [ ] The tooltip number should be shown to two decimal places.
- [ ] The legend bands should be shown to two decimal places.

Please get in touch if you have any questions.

**Comment by Duncan-Knox** [comment]
Hi @epicallan (and @dw8547 FYI),  please see update on checks to global picture IOF staging:

The following series listed below have been checked and are fine. I have completed the addition of changes to global picture concept.csv on these also:

- Gross ODA received (fact.in_oda_gross)
- Net ODA received, (fact.in_oda_net)
- Net ODA provided by OECD DAC members (fact.out_oda_net)
- Net ODA provided by DAC members, % of GNI (fact.oda_percent_gni)
- Gross ODA provided by DAC members to LDCs, % of GNI (fact.oda_to_ldcs_percent_gni)

The following series are in a state of limbo regarding the feasibility of using the new methodology. I am afraid it is not possible for me to provide an expected time at which we'll know a definite answer on this. I would also need to update concepts csv for these also.

- Gross other official flows received
- Net other official flows provided

The following are awaiting instructions to automate and have not been updated on staging.

- Net south-south development cooperation provided
- South-south development cooperation provided, % of GNI

**Comment by epicallan** [comment]
Hi @dw8547

Thanks for the updates. I will restart the staging app to clear cache, so that the new updates take effect.

cc @Duncan-Knox

**Comment by Duncan-Knox** [comment]
Hi @epicallan I've updated concepts csv for new data. Happy for these to be pushed live.

**Comment by Duncan-Knox** [comment]
Thank you @dw8547. 

The metadata CMS updates are complete @epicallan.

**Comment by dw8547** [comment]
@Duncan-Knox, woo!
