### ISSUE TITLE
Unbundling AID (ODA)

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub#154]

**Comment by Duncan-Knox** [comment]
@dw8547 I'd like to attempt to fix the possible bug in the bundle coding before this is pushed live. This would involve looking at the details of the coding sequence, specifically for type D 'gpgs-nngos'. Please can we begin on this after out-ssc-net and out-ssc-net-percent-gni are ready?

**Comment by dw8547** [comment]
Hi @Duncan-Knox, yes of course. In the meantime, below are the details of the ODA unbundling logic. There were designed @robtew and were meant to mirror the behaviour of the unbundling as implemented in Excel. This means that, technically speaking, the unbundling logic set up forces the results to be of a desired type. This type is not necessarily the most optimal or even the natural. Please take a look at this and we can unpick this + fix. 

The logic is based on a series of "IF → THEN → ELSE" statements evaluated in sequence. This means that the order in which they are applied matters. All of the "IF → THEN → ELSE" statements look at one or several CRS columns in order to decide which bundle a CRS record (row) will be assigned. The statements are applied to a subset of the data where the following is true:

 category | flow_code | flow_name
---|---|---
10 | 11 | ODA Grants
10 | 13 | ODA Loans
10 | 19 | Equity Investment

The statements look to assign one of the following bundles to each CRS record:

 code |          id          |                              name                              
------|----------------------|----------------------------------------------------------------
 A    | cash-loan-equity     | Cash (loan/equity)
 B    | cash-grant           | Cash grant
 C    | commodities-food     | Commodities and food
 D    | gpgs-nngos           | Global initiatives and northern non-governmental organisations
 E    | mixed-project-aid    | Mixed project aid
 F    | non-transfer         | Non-transfer
 G    | technical-ooperation | Technical cooperation

 The "IF → THEN → ELSE" statements are, in order of evaluation:
```
                        -- F
                        WHEN aid_type = $$E01$$ THEN $$F$$
                        WHEN aid_type = $$E02$$ THEN $$F$$
                        WHEN aid_type = $$G01$$ THEN $$F$$
                        WHEN aid_type = $$H01$$ THEN $$F$$
                        WHEN aid_type = $$H02$$ THEN $$F$$
                        WHEN finance_type = 210 THEN $$F$$
                        WHEN sector_code = 600 THEN $$F$$
                        WHEN purpose_code = 93010 THEN $$F$$
                        WHEN purpose_code = 99820 THEN $$F$$

                        -- A
                        WHEN flow_code = 13 THEN $$A$$
                        WHEN flow_code = 19 THEN $$A$$

                        -- G
                        WHEN aid_type LIKE $$D%$$ THEN $$G$$
                        WHEN ftc = 1 THEN $$G$$

                        -- B
                        WHEN aid_type = $$A01$$ THEN $$B$$
                        WHEN aid_type = $$A02$$ THEN $$B$$

                        -- C
                        WHEN purpose_code = 52010 THEN $$C$$
                        WHEN purpose_code = 53030 THEN $$C$$
                        WHEN purpose_code = 53040 THEN $$C$$
                        WHEN purpose_code = 72040 THEN $$C$$

                        -- B
                        WHEN (aid_type = $$B01$$ AND recipient_code != 998) THEN $$B$$

                        -- D
                        WHEN (aid_type = $$B01$$ AND recipient_code = 998) THEN $$D$$

                        -- B
                        WHEN (aid_type = $$B03$$ AND recipient_code != 998) THEN $$B$$

                        -- D
                        WHEN (aid_type = $$B03$$ AND recipient_code = 998) THEN $$D$$

                        -- B
                        WHEN (aid_type = $$B04$$ AND recipient_code != 998) THEN $$B$$

                        -- D
                        WHEN (aid_type = $$B04$$ AND recipient_code = 998) THEN $$D$$

                        -- B
                        WHEN purpose_code = 51010 THEN $$B$$
                        WHEN CAST(channel_code AS CHARACTER(5)) LIKE $$3____$$ THEN $$B$$
                        WHEN pba = 1 THEN $$B$$

                        -- D
                        WHEN CAST(channel_code AS CHARACTER(5)) LIKE $$51___$$ THEN $$D$$

                        -- B
                        WHEN
                        (donor_code = 901 OR
                        donor_code = 905 OR
                        donor_code = 906 OR
                        donor_code = 907 OR
                        donor_code = 909 OR
                        donor_code = 912 OR
                        donor_code = 913 OR
                        donor_code = 914 OR
                        donor_code = 915 OR
                        donor_code = 916 OR
                        donor_code = 921 OR
                        donor_code = 951 OR
                        donor_code = 976 OR
                        donor_code = 990) AND
                        usd_disbursement >= 1 THEN $$B$$
                        WHEN (LOWER(short_description) ILIKE $$%finance%$$ OR LOWER(short_description) ILIKE $$%financement%$$) THEN $$B$$
                        WHEN (LOWER(short_description) ILIKE $$%fund%$$ OR LOWER(short_description) ILIKE $$%fonds%$$) THEN $$B$$
                        WHEN (LOWER(short_description) ILIKE $$%subsidy%$$ OR LOWER(short_description) ILIKE $$%subsidie%$$) THEN $$B$$
                        WHEN (LOWER(long_description) ILIKE $$%finance%$$ OR LOWER(long_description) ILIKE $$%financement%$$) THEN $$B$$
                        WHEN (LOWER(long_description) ILIKE $$%fund%$$ OR LOWER(long_description) ILIKE $$%fonds%$$) THEN $$B$$
                        WHEN (LOWER(long_description) ILIKE $$%subsidy%$$ OR LOWER(long_description) ILIKE $$%subsidie%$$) THEN $$B$$
                        WHEN long_description LIKE $$% SWAP %$$ THEN $$B$$

                        -- D
                        WHEN (LOWER(long_description) ILIKE $$%research%$$ AND recipient_code = 998) THEN $$D$$

                        -- G
                        WHEN LOWER(short_description) ILIKE $$%consultancy%$$ THEN $$G$$
                        WHEN LOWER(short_description) ILIKE $$%consultant%$$ THEN $$G$$
                        WHEN LOWER(short_description) ILIKE $$%technical assistance%$$ THEN $$G$$
                        WHEN LOWER(short_description) ILIKE $$%technical cooperation%$$ THEN $$G$$
                        WHEN LOWER(short_description) ILIKE $$%training%$$ THEN $$G$$
                        WHEN LOWER(long_description) ILIKE $$%consultancy%$$ THEN $$G$$
                        WHEN LOWER(long_description) ILIKE $$%consultant%$$ THEN $$G$$
                        WHEN LOWER(long_description) ILIKE $$%technical assistance%$$ THEN $$G$$
                        WHEN LOWER(long_description) ILIKE $$%technical cooperation%$$ THEN $$G$$
                        WHEN LOWER(long_description) ILIKE $$%training%$$ THEN $$G$$

                        -- C
                        WHEN (LOWER(short_description) ILIKE $$%vaccin%$$ OR LOWER(short_description) ILIKE $$%vacci%$$) THEN $$C$$
                        WHEN (LOWER(short_description) ILIKE $$%non-food%$$ OR LOWER(short_description) ILIKE $$%nonfood%$$ OR LOWER(short_description) ILIKE $$%non alimentaire%$$) THEN $$C$$
                        WHEN (LOWER(long_description) ILIKE $$%vaccin%$$ OR LOWER(long_description) ILIKE $$%vacci%$$) THEN $$C$$
                        WHEN (LOWER(long_description) ILIKE $$%non-food%$$ OR LOWER(long_description) ILIKE $$%nonfood%$$ OR LOWER(long_description) ILIKE $$%non alimentaire%$$) THEN $$C$$

                        -- E
                        ELSE $$E$$
```

@Duncan-Knox, please get in touch when you have checked this and are ready to start the work on correcting.

**Comment by Duncan-Knox** [comment]
@dw8547 Checking now complete with input from Rob Tew. Ready to start work on checking when you are.

**Comment by dw8547** [comment]
@Duncan-Knox, Monday AM please (?) if it needs face to face/voice/interactive comms. 

If it's a case of moving things around, changing things and/or adding or removing things, please post here: https://github.com/devinit/ddw-data/issues/63

E.g.:

- change `WHEN (aid_type = $$B01$$ AND recipient_code != 998) THEN $$B$$` to `WHEN (aid_type = $$B01$$ AND recipient_code != 9988) THEN $$B$$`

If this is the case, please number the "IF → THEN → ELSE" statements and leave instructions next to each, e.g.:

1) `WHEN aid_type = $$E01$$ THEN $$F$$`: no change
2) `WHEN aid_type = $$E02$$ THEN $$F$$`: no change
3) `WHEN aid_type = $$G01$$ THEN $$F$$`: move to position 4
4) `WHEN aid_type = $$H01$$ THEN $$F$$`: move to position 3

etc.

Does this make sense?

**Comment by dw8547** [comment]
@epicallan, @Duncan-Knox, data with fix in `fact.oda_2015_new`, ready to be used. Relevant [concept.csv](https://github.com/devinit/datahub-cms/blob/master/unbundling-oda/concept.csv) updated.

**Comment by epicallan** [comment]
Hi @Duncan-Knox & @dw8547 

Updated ODA data is available on staging for cross checking.

http://212.111.41.68:8080/unbundling-aid

Thanks

**Comment by epicallan** [comment]
- [ ] unbundling aid drop downs not working in IE
