### ISSUE TITLE
Data-warehouse data API functions for various visualizations

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub#2]
Resolver functions

- [x] Global maps 
- [x] unbundling aid  &  unbundling other official flows
- [x] country profiles 
- [x] country spotlights
- [x] where are the poor and where will they be
- [x] bubble charts in other visualisation tab

**Comment by epicallan** [comment]
@dw8547 why ``di_id``and not ``id`` for tables in data_series schema ?

**Comment by dw8547** [comment]
Good morning @epicallan. All of the table in the `data_series` schema are maintained by the analysts. This means that I don't populate the tables but the analysts do. Where we have updated a table in the recent past (think January 2017) I have tried to enforce the standard column names `di_id`, `from_di_id`, `to_di_id` where applicable. Where you see a column called `id` that means that the table has not been updated in a very long time and that the table was created before we had a data model and before I joined the company. I prefer `di_id` to `id` as `id` could be anything whereas we have now settled on what a `di_id` refers to.

Do you need all `id` to be changed to `di_id`?
