### ISSUE TITLE
Bug with ODA data display

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#200]
http://data.devinit.org/unbundling-aid

When I tried to select 2016 from the drop down menu it was not allowing me to check this option.

I think we have a bug.

**Comment by epicallan** [comment]
Hi @k8hughes 
2016 shouldn't be there. It just sneaked in there during some partial updates of the site. This will be corrected in a fresh build. Early next week.

**Comment by epicallan** [comment]
it was solved
