### ISSUE TITLE
Rounding error in recipient profile, "How is income distributed?" chart 

### ISSUE THREAD

**Issue by dw8547** [devinit/datahub#237]
Hi @epicallan, there is a rounding issue going on in the "How is income distributed?" chart on a recipient country profile. For example, see: http://data.devinit.org/country/albania. Figure above red bar for Albania in 2012 = 8.9% while the figure in the text for Albania in 2012 = 8.8. The actual figure is 8.85%, see attached.
![screenshot from 2018-03-02 11 02 13](https://user-images.githubusercontent.com/10259585/36896304-0d15e900-1e0a-11e8-9a4b-3824a015aa50.png)

**Comment by epicallan** [comment]
This was fixed on staging, will be live on live site the next time we update it

**Comment by dw8547** [comment]
Thanks @epicallan. @Duncan-Knox will have to check live/confirm/close.

**Comment by epicallan** [comment]
This was fixed cc @Duncan-Knox
