### ISSUE TITLE
Spotlight on kenya data update

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub#299]

**Comment by epicallan** [comment]
@mrsbett about writing the figures in full, that was decided way back and it may be more work that its worth to change at the moment.

About the typos, thanks for spotting those going to be corrected in a few.

**Comment by Duncan-Knox** [comment]
Hi @mrsbett, a couple of questions from me: 

Would it be beneficial to state what the national poverty line is in the poverty headcount indicator description?

Would the 'human development index' indicator visual benefit from the legend and labels being shown to two decimal places? There are ones in different colour bands showing the same score, e.g. Nairobi and Kajiado?

Best, Duncan

**Comment by mrsbett** [comment]
@duncan, both suggestions make a lot of sense- is this possible @epicallan

**Comment by stevekenei** [comment]
There is no one specific poverty line. There are two lines, for rural and urban. Thus defined officially as: "households and individuals whose monthly adult equivalent total consumption
expenditure per person is less than Ksh 3,252 in rural and peri-urban areas and less than Ksh
5,995 in core-urban areas are considered to be overall poor or live in “overall poverty”." We can include that in our definition, but without knowledge on area definition, it won't make sense to everyone where on the map is rural, peri urban etc

**Comment by stevekenei** [comment]
@Duncan-Knox , I like the idea of providing more technical notes. Let us put it high on our priority list. It maybe a requirement necessary for the entire spotlight platform. For now, given the devolution conference starts this Monday, let us do the typo edits and revisit definitions soon after......

**Comment by Duncan-Knox** [comment]
@stevekenei, great, in agreement. One final point from me, it was spotted by Richard (who has more experience working on maps that I) that the 'Hardcore poverty Headcount' map has three colours showing, with the largest bands on the legend not in use. Would altering the bands be an enhancement?

**Comment by epicallan** [comment]
@mrsbett @stevekenei the typo corrections were fixed

**Comment by stevekenei** [comment]
@Duncan-Knox Great spot! Yes, let's alter the bands @epicallan have the largest being >50%, so <10%, 10-20%, 30-40%, 40-50% and >50%

**Comment by epicallan** [comment]
I have updated staging and live site with recommended changes
cc @stevekenei
