### ISSUE TITLE
Uganda spolight data update

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#325]

**Comment by Napho** [comment]
Meeting with Moses and Esther to review July 2018 Spotlight update completed, I will update the concept.csv file to reflect the the fields that is expected for each row of the concept diagram, the rows match the tables that are available in the given schema and share with Moses tomorrow. Only new data will be updated, the current database data does not have much changes to it

**Comment by k8hughes** [comment]
@edwinmp can you add a note here about what is still to do?

**Comment by edwinmp** [comment]
- [ ] Education: - Secondary students with adequate sitting and writing space (government schools) - 2014, 2016
- [ ] Education: - Secondary students with adequate sitting and writing space (total) - Buliisa district
- [ ] Health: - Primary health spending per person - 2018, 2019

Esther will be testing again to find any other discrepancies.
