### ISSUE TITLE
Domestic.csv data collection and sign off

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#329]
This comes in stages:
* Data scraping
* Data checking
* Data update

**Comment by Duncan-Knox** [comment]
Awaiting email clarification on sign-off time from RW.

**Comment by k8hughes** [comment]
I am changing this issue to reflect the process for data collection and sign off only, Duncan to creat new issue for data update.

**Comment by k8hughes** [comment]
End of next week for update of the key countries. 
All countries won't be ready till after ITEP launch.

**Comment by k8hughes** [comment]
@akmiller01 is there a link that we can put on this issue that would show what version of the file has been added to staging.

**Comment by akmiller01** [comment]
Updated output is always here: https://github.com/devinit/domestic_finance_2018/tree/master/output With a timestamp of when it was last updated.
