### ISSUE TITLE
Add URL's to global picture to improve user experience and allow for better analytics

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#330]
Currently all of the second level nav all uses the same URL http://data.devinit.org/ 

Need to change this.

**Comment by edwinmp** [comment]
Hi @k8hughes, updated the staging server with a functional version. Please have a look.
http://212.111.41.68:8080/

**Comment by k8hughes** [comment]
Perfect.
LGTM!

**Comment by edwinmp** [comment]
The links have been added and the change deployed.
