### ISSUE TITLE
Adding a link from Spotlight on Uganda back to the country Profile for Uganda.

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#331]
This page:  http://data.devinit.org/spotlight-on-uganda 

Needs to have a link either a a button or clearly in text that points back to this profile:  http://data.devinit.org/country/uganda

**Comment by edwinmp** [comment]
Hi @k8hughes,

Added the link to the country pages, but I thought it'd be best to do it for both Uganda & Kenya. Need your thoughts on the link location though. Top left, below the logo.

![image](https://user-images.githubusercontent.com/5672438/42631442-e9a78d70-85e2-11e8-842a-bca0627dcfce.png)

**Comment by k8hughes** [comment]
I like the location and the way you have used the flag but I think it might need some text to make it clear to a user that this is a link.

Can you try adding "country profile"? I assume there will be interaction on hover over that would tell the user it is linked.

Great work!

**Comment by edwinmp** [comment]
Given it's top-left position, adding "country profile" makes it look like a heading & thus everything below it should be about the country profile :)

![image](https://user-images.githubusercontent.com/5672438/42633826-492b32a4-85ea-11e8-93ef-4b7fa294f947.png)

DI red is the colour for links. To stick to the theme, the alternative is dark grey. Any other colour would stick out. To make it look less like a heading, can move it to the top right instead. In grey, it turns red when hovered on.

![jul-12-2018 15-59-58](https://user-images.githubusercontent.com/5672438/42634914-4b2ffc4e-85ed-11e8-8b81-51e9e87a778a.gif)

**Comment by k8hughes** [comment]
The solution you have just shared is great.  

👍  LGTM.

**Comment by edwinmp** [comment]
Change added and deployed.
