### ISSUE TITLE
Adding a link from the Spotlight on Kenya back to the country profile for Kenya

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#332]
There need to be reciprocal links so from this page: http://data.devinit.org/spotlight-on-kenya 

you are told about this page: http://data.devinit.org/country/kenya 

and vice versa

This can be done as links in text or a button, which ever makes the most sense from the FE dev point of view.

**Comment by edwinmp** [comment]
This is fixed and deployed.
