### ISSUE TITLE
Produce and update global picture vulnerability data

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#334]

**Comment by akmiller01** [comment]
Update script is here: https://github.com/devinit/ddh_donata_scripts/blob/6e264331d2440edfd43c2834e40c1571cc8c9fcd/data_extraction/di_data_hub_mirror/data_hub_db/CREATE_TABLE_vulnerability.sql

Database names seem to be:

1. `data_series.fragile_states`
2. `data_series.climate_vulnerability`
3. `data_series.human_hazard`
4. `data_series.natural_hazard`
5. `data_series.number_of_un_appeals`
6. `data_series.forgotten_crisis`
7. `data_series.displacement`

**Comment by edwinmp** [comment]
@Duncan-Knox, could you please verify this update. Thanks.
