### ISSUE TITLE
Updating the 'International Finance' tab indicators on the Global Picture

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#335]

**Comment by edwinmp** [comment]
Hi @Duncan-Knox , pulled in the Global Picture data on International Finance from the CMS & updated the staging environment. Please test and let me know if it all came through as required.
http://212.111.41.68:8080

**Comment by Duncan-Knox** [comment]
As a follow up to the comment above. I've spoken to Zach and he has confirmed the new poverty data has not come through on staging. Therefore the poverty data and the two global picture indicators data have been submitted today to @Napho for uploading on the database at a convenient time. We will soon get data for other global picture indicators too. @edwinmp what are your plans for pushing these live, would it have to go live when the spotlight on Uganda is pushed live, or wait until more are ready?

**Comment by edwinmp** [comment]
@Duncan-Knox Won't be pushing to live anytime soon. The correct process is to get together and plan for a release, make a list of all the features we'd like that particular release to contain, come up with a timeline and then build towards it. That particular release is then pushed to live once all the planned features are complete & tested.
We can attempt to have minor change releases every month (if they're stable), and major releases every quarter, but ultimately it's all about what features we want in a release and how soon we complete them.

To get the ball rolling on this, I suggest you or @k8hughes make a list of all pending changes and we can decide which ones we can group to release together based on priority and dependency.

**Comment by edwinmp** [comment]
Hi @Duncan-Knox, I'm unsure whether this task is done or not. Could you please verify. Thanks.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp @Napho as discussed the staging site still shows previously submitted data as opposed to newly submitted data for data_series.fdi_pp and data_series.remittances_pp

**Comment by Duncan-Knox** [comment]
Hi @edwinmp @Napho I still cannot see the data coming through onto staging for the fixed data_series.fdi_pp and data_series.remittances_pp, was there a pull through here?

**Comment by Napho** [comment]
Hi Duncan,

There is an issue with the cache implementation, try running with the
browser in incognito mode, that way no data will be cached and new data
will always be pulled. We'll try to find the best way around it for what we
dobt want cached later..

Thanks

**Comment by Duncan-Knox** [comment]
Hi @Napho thank you. I'll bear this in mind for future reference. The data looks like it is coming through fine now. Great to have this one complete now, Happy to sign-off.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp one tweak here would it please be possible to make the no data countries grey on remittances per person? E.g United Kingdom shows up as blue when it has no data. Would you prefer a separate bug issue for this request?

**Comment by edwinmp** [comment]
Hi @Duncan-Knox, I can't find where this is happening in International Finance. The default is always grey for no data, so if there's somewhere it's not that way, then it's a bug.

**Comment by edwinmp** [comment]
Ahh, found it... remittances per person. Hmm... that seems intentional. Will see if I can set it to the usual grey & keep things consistent.

**Comment by Duncan-Knox** [comment]
Ok let's catch-up on then when you are next free. Interesting that it is intentional I'd like to hear the details on why/how this is in place on the coding. We may need to discuss this point on the poverty data too, which may have intentional colouring for countries with no data, I'll need to speak to the data lead.

**Comment by edwinmp** [comment]
@Duncan-Knox Actually, there's a subtle difference here. There's two instances;

1. There's no data at all (no record in the database for this indicator on this country). These are the grey ones. The label for these is usually just "No data"
2. The data specifically indicates there is no data for a particular indicator on a particular country. These are the lightest blue. The label for these is in the format "No data in 2016"

**Comment by Duncan-Knox** [comment]
@edwinmp this is quite odd. These separate instances do not seem to be the case on the live site, only on staging. I'd recommend reverting to the point 1 for all countries with "no data" or no value. ie similar to 'Largest international resource flow', I can't explain why this is the case that this indicator has a separate setting on staging. How feasible would this be to implement?

**Comment by Napho** [comment]
@Duncan-Knox this could be issue with data migration from production to set up staging, I set up staging with latin1 and production has been utf8, had to change it only when started work on spotlight data, its possible that some data may not  have been added to staging, i will look at these

**Comment by Duncan-Knox** [comment]
Hi @Napho ok interesting. Thanks for looking at these. In this instance this feels less an issue with missing data points and more an issue that those countries which we know have missing data have a setting which gives them a colour when it ought to be greyed out. However, I was wondering if this issue you raise is having or likely to have other effects on the staging?

**Comment by edwinmp** [comment]
@Duncan-Knox This seems to be a regression that's not in the scope of the current issue. Could you please create a separate issue for it.

**Comment by edwinmp** [comment]
Update made and deployed.
