### ISSUE TITLE
Visual Bug on Global Picture

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#339]
The text that describes the visual and gives the colour key for the map over laps with the country info hover over.
AFAICT this effects all browsers.

**Desired behaviour:** the country info that appears on hover over shouldn't be able to over lap with the explanitory text.  Hoverover detail box should have a limited sphere of movement so it cannot overlap.
 
![screen shot 2018-07-16 at 16 10 57](https://user-images.githubusercontent.com/36768381/42766890-7f78bf12-8913-11e8-8be8-b91c5c9f2309.png)

**Comment by edwinmp** [comment]
Hi @k8hughes, I went with a simpler fix, which is to make the tooltip appear above all else when it's showing. The user can simply hover out if they want to read explanatory text.

![jul-12-2018 15-59-58](https://user-images.githubusercontent.com/5672438/42866000-03dea008-8a74-11e8-9366-ce0de9ad5496.gif)

**Comment by k8hughes** [comment]
LGTM

**Comment by edwinmp** [comment]
Fixed and deployed.
