### ISSUE TITLE
Bug on Global Picture poverty 'Number of people in the P20'

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#341]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**

Global picture poverty tab: the 'Number of people in the P20' indicator does not load on the map.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'Global Picture'
2. Click on 'Poverty'
3. Scroll down to 'Number of people in the P20'

**Expected Behaviour**

Indicator should load to show data on the map.

**Screenshots/GIF**

![image](https://user-images.githubusercontent.com/13347058/42808954-4aa36ea6-89ac-11e8-8114-e2a9c53e47f5.png)

**Desktop (please complete the following information):**

Chrome and Firefox

**Environment/Server:**
<pre><code>
- [X] Production
- [X] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: 30/07/2018

**Comment by edwinmp** [comment]
Hi @Duncan-Knox, discovered a potentially related bug while troubleshooting this one. Navigating away from poverty to any other tab and then navigating back to poverty seems to maintain the data & colours of the previous tab.
Will investigate and see if they're related.

**Comment by edwinmp** [comment]
Seems to also happen when navigating to/from "Forward Looking ODA"

**Comment by Duncan-Knox** [comment]
Hi @edwinmp, good spot, I hadn't noticed this one. I'm getting it for data revolution also. Definitely something up with that. Let me know how the investigation goes.

**Comment by edwinmp** [comment]
@Duncan-Knox They're unrelated. Going to work on this one first as it's coming from the API side. Could you please create a separate issue for the tab switching bug.
Thanks.

**Comment by Duncan-Knox** [comment]
@edwinmp ok noted. Sure will create a separate bug now.

**Comment by edwinmp** [comment]
Hi @Duncan-Knox ... this is fixed on staging. Please have a look.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp thank you. On review, the fix has gone through fine on the staging page.

**Comment by edwinmp** [comment]
Fixed and deployed.
