### ISSUE TITLE
Bug on Global Picture International finance 'largest international resource flow'

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#342]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Hover over tool tip on the global picture international finance indicators 'largest international resource flow' states the number code for the largest international resource flow, as opposed to the name of the flow on the label

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'Global Picture'
2. Click on 'International Finance'
3. Scroll down to 'Largest international resource flow'

**Expected Behaviour**
Tool tip hover over should show the label naming resource flow as opposed to the code number

**Screenshots/GIF**
![image](https://user-images.githubusercontent.com/13347058/42809363-6a297256-89ad-11e8-8620-9a4f3358196c.png)

**Desktop (please complete the following information):**

Chrome
Firefox

**Environment/Server:**
<pre><code>
- [x] Production
- [x] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: 20/07/2018

**Comment by Duncan-Knox** [comment]
Edit: good spot Edwin, this one occurs on the 'fragile states' indicator on the vulnerability tab also.

**Comment by edwinmp** [comment]
Hi @Duncan-Knox, fixed this. Please verify on staging.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp fix verified on staging for both 'largest international resource flow' and 'fragile states'

**Comment by edwinmp** [comment]
Fixed and deployed.
