### ISSUE TITLE
Bug [2] on Government revenue, financing and expenditure

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#344]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A number of bugs crop up on the Government revenue, financing and expenditure section of the digital country profiles, one here is the box bursts can disappear when the interactive sliders are used. These are replaced with a 'React component has an error!' statement.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'Country profiles'
2. Click on 'A country profile'
3. Scroll down to 'Government revenue, financing and expenditure'
4. Activate the interactive slider.
5. See error

**Expected Behaviour**
 
Box bursts ought not to disappear

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.
![image](https://user-images.githubusercontent.com/13347058/42810370-aadddd62-89af-11e8-90a9-f741ae2ccca4.png)

**Desktop (please complete the following information):**

Chrome
Firefox

**Environment/Server:**
<pre><code>
- [x] Production
- [x] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**
There are a number of bugs on the Government revenue, financing and expenditure section of the digital profiles and different bugs seem to appear at random when they are used.

Requested Delivery Date: 30/08/2018

**Comment by Duncan-Knox** [comment]
Hi @edwinmp great to see this fixing work to allow these charts to get up and running again. I think the issues here may be more complex than originally thought. There are still instances of the bug originally flagged occurring, although the severity of the bug has definitely been lessened. 

I've spoken to Richard the content lead on these and he's stated that the fix of removing the first layer is not workable for these as the hierarchy would always have financing stated first. The fix is looks to be a further deviation from the issue in this case. We believe that the problem stems from potential broken coding which would have been used to treat negative figures in the data. The data has a series of negative figures in, which would explain your comment in the meeting today about totals not matching. The negatives were shown in the charts too originally. We are trying to dig up a screenshot for how this looked and are free to discuss the issue in more detail at any time that suits you.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp yes this bug is fixed. However I may flag a couple more bugs for this visualisation on the Kanban.

**Comment by edwinmp** [comment]
Fixed and deployed.
