### ISSUE TITLE
Bug on PDFs for Korea and North Korea

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#345]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Download and print PDFs for Korea and North Korea do not open. Good spot

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'Country profile for Korea or North Korea'
2. Click on 'Download and Print'
3. See error

**Expected Behaviour**
PDF should load

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.
![image](https://user-images.githubusercontent.com/13347058/42868460-4d0e9e54-8a6a-11e8-866c-ce3c475db564.png)

**Desktop (please complete the following information):**

Chrome
Firefox

**Environment/Server:**
<pre><code>
- [X] Production
- [X] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**
Is there a way of quickly checking all PDFs are working or should I go through each one and check?

Requested Delivery Date: 25/08/2018

**Comment by edwinmp** [comment]
@Duncan-Knox Currently unable to conclusively determine how the PDFs are generated. That's not a requirement for solving the South Korea bit, but is for the North Korea PDF which is missing. For the South Korea, failed to clone the repo because it's massive and the damn internet connection is soooo slow. So I'm marking this task others dependent on figuring out the PDF process as blocked.
Have consulted Alex, but perhaps Cecilia may have better insight on this since she's made commits to the PDF repo. Will inquire from her.

**Comment by Duncan-Knox** [comment]
@edwinmp thanks for the update. It's possible North Korea had it's PDF status removed given a lack of data. I'm not sure we have records on these kind of decisions. I doubt this is the case as we have PDFs for other countries with similar data paucity, I'll revisit the issue, in the case the PDF is not to be shown it would be a case of removing the download and print button.

**Comment by k8hughes** [comment]
Bahrain is giving the same message.  Cannot GET.  Should I check every country?  @edwinmp new issue or the same one?

**Comment by k8hughes** [comment]
Cannot GET /pdf/20170331/Andorra.pdf
Cannot GET /pdf/20170331/Anguilla.pdf
Cannot GET /pdf/20170331/Antigua-&-Barbuda.pdf
Cannot GET /pdf/20170331/Barbados.pdf
Cannot GET /pdf/20170331/Bosnia-&-Herzegovina.pdf
Cannot GET /pdf/20170331/C%C3%B4te-d'Ivoire.pdf
Cannot GET /pdf/20170331/Cuba.pdf
Cannot GET /pdf/20170331/Mayotte.pdf
Cannot GET /pdf/20170331/Montserrat.pdf
Cannot GET /pdf/20170331/Nauru.pdf
Cannot GET /pdf/20170331/Niue.pdf
Cannot GET /pdf/20170331/Oman.pdf
Cannot GET /pdf/20170331/Papua-New-Guinea.pdf
Cannot GET /pdf/20170331/Saint-Kitts-and-Nevis.pdf
Cannot GET /pdf/20170331/Sao-Tome-&-Principe.pdf
Cannot GET /pdf/20170331/Slovak-Republic.pdf
Cannot GET /pdf/20170331/Somalia.pdf
Cannot GET /pdf/20170331/Thailand.pdf
Cannot GET /pdf/20170331/Tokelau.pdf
Cannot GET /pdf/20170331/Trinidad-&-Tobago.pdf
Cannot GET /pdf/20170331/Turks-&-Caicos-Islands.pdf
Cannot GET /pdf/20170331/Wallis-&-Futuna.pdf
Cannot GET /pdf/20170331/Western-Sahara.pdf

I have clicking through and these are all the ones with this error message.

**Comment by edwinmp** [comment]
Hi @k8hughes, the countries above all have their Download & Print button removed.

**Comment by edwinmp** [comment]
@k8hughes On production too.

**Comment by k8hughes** [comment]
LGTM
