### ISSUE TITLE
Bug on Global Picture poverty

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#346]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**

On Global Picture navigating away from poverty to any other tab and then navigating back to poverty seems to maintain the data & colours of the previous tab. Seems to also happen when navigating to/from "Forward Looking ODA". This also seems to be in effect for other tabs such as data revolution.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'Global picture'
2. Click on 'Poverty tab'
3. Click on 'Another tab'
4. Click on 'Poverty tab'
5. See error: colours stay the same.

**Expected Behaviour**
Colours move to the relevant indicator.

**Desktop (please complete the following information):**
Chrome

**Environment/Server:**
<pre><code>
- [X] Production
- [X] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**
Unrelated to https://github.com/devinit/datahub/issues/341#issuecomment-405838145

Requested Delivery Date: 30/08/2018

**Comment by edwinmp** [comment]
Hi @Duncan-Knox, fixed this. Please verify on staging.

**Comment by Duncan-Knox** [comment]
Thank you @edwinmp I can confirm this is fixed on staging.

**Comment by edwinmp** [comment]
Fixed and deployed.
