### ISSUE TITLE
Bug on naming for Côte D'Ivoire

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#347]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
On the global map pane when the browser is on an individual country profile, the tool tip for Côte D'Ivoire displays the name similar to when there is a file origin error.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'A country profile'
2. Hover over Côte D'Ivoire on the global map pane

**Expected Behaviour**
To state Côte D'Ivoire

**Screenshots/GIF**

![image](https://user-images.githubusercontent.com/13347058/42930286-782607a6-8b34-11e8-835e-45a15194775a.png)

**Desktop (please complete the following information):**

Chrome

**Environment/Server:**
<pre><code>
- [X] Production
- [X] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**
Does not seem to occur for other mentions of Côte D'Ivoire

Requested Delivery Date: 01/12/2018 - low priority

**Comment by edwinmp** [comment]
Hi @Duncan-Knox, this should be fixed on staging. Please review.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp, thank you. Fix confirmed successful.

**Comment by edwinmp** [comment]
Fixed and deployed.
