### ISSUE TITLE
Bug on country digital profiles: international resources: inflows over time

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#349]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Country profiles > international resources > tree visualisation:
When ODA is selected the default is to show breakdown by provider. Selecting any other dimension (sector, channel etc) crashes the page -error message in producing chart and can’t then return to provider selection either.

This is the case for both donor profiles and recipient profiles.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'Digital country profile'
2. Click on 'tab for international resources'
3. Scroll down to 'inflows over time'
4. Click on 'official development assistance' on the left scroll down
5. Click on another dimension on the right side scroll down, e.g. sector
6. See error
7. Try clicking back onto providers on the right hand side.
8. See error

**Expected Behaviour**
Does not crash when clicked on and user can navigate successfully between options.

**Screenshots/GIF**

![gif for bug ddh](https://user-images.githubusercontent.com/13347058/42956958-2f2e1b02-8b79-11e8-90f0-381e0f016e8c.gif)

**Desktop (please complete the following information):**
Chrome

**Environment/Server:**
<pre><code>
- [X] Production
- [X] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**
As noted this is the case for both donor and recipient files.

Requested Delivery Date: 30/07/2018

**Comment by edwinmp** [comment]
Hi @Duncan-Knox ... this should be fixed. Please review on staging.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp thank you. I have reviewed on staging, the fix has gone through successfully.

**Comment by edwinmp** [comment]
Fixed and deployed.
