### ISSUE TITLE
Overlay is out of alignment

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#353]
**Describe the issue**

The overlay on the page does not line up with what is underneath. When pressing on the tab using the visualisation it comes up with an overlay, but this is all shunted too far up and left, meaning that the notes on the overlay are out of sink with what it is supposed to be explaining.

**To Reproduce**
To to ‘Profiles’
Go to ‘Country Profiles’

Click on ‘type country name’
Click on Afghanistan
Click ‘jump to country finance’
Click ‘using this visualisation’

Or any tab with "use this visulisation"

**Expected Behaviour**
The writing on the overlay perfectly with what it is pointing to underneath.

A clear and concise description of what you expected to happen

**Screenshots/GIF**
![screen shot 2018-07-27 at 10 40 39](https://user-images.githubusercontent.com/36768381/43314003-8a98213e-9189-11e8-8b48-7dd1dc077494.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS 10.13.6
 - Browser Crome, Firefox texted

**Environment/Server:**
<pre><code>
- [ x] Production
- [ ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**
This is not a regression, AFAIK it has always been the case

Low priority

**Comment by k8hughes** [comment]
intro.js. looks really cool.  Love this idea!  Great solution.  How long would this take to implement?

**Comment by edwinmp** [comment]
Shouldn't take long... I'm hoping to have a basic implementation done by end of day.

**Comment by k8hughes** [comment]
Excellent.

**Comment by edwinmp** [comment]
Hi @k8hughes ... new implementation is done on staging. Please have a look. Used the wording of the previous overlay, but I could update that as well if you have any suggestions.

**Comment by k8hughes** [comment]
The numbering goes off screen on my screen size.  Can you adjust it so it works for different sizes?  Love the way this works though it is much nicer.

![screen shot 2018-08-23 at 14 42 26](https://user-images.githubusercontent.com/36768381/44528988-e6373e80-a6e2-11e8-8928-2f3c18df2c04.png)

**Comment by k8hughes** [comment]
LGTM!
