### ISSUE TITLE
Text on graphs not fitting within boxes, so not showing.

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#354]
## i’m submitting a bug

**describe the issue**
The writing in one of the boxes is half hidden, you cannot read it properly. 

**to reproduce**
Go to ‘profiles’
Go to ‘country profiles’
Go  to ‘type country name’
Click Afghanistan 
Go to jump to country finances
Will display revenue and grants 
Keep one of the criteria to constant 2015 USD
Look to the box ‘grants to development budget’
The error is there

**Expected behaviour**
To see all of the text

**Screenshots/GIF**
﻿
![screen shot 2018-07-27 at 10 49 38](https://user-images.githubusercontent.com/36768381/43314428-cc8230fc-918a-11e8-9187-deaec6627569.png)

**Desktop**
 - OS: 10.13.6
 - Browser Firefox

**Environment/Server:**
<pre><code>
- [ x] Production
- [ ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**
This type of error occurs in several places, text not fitting within boxes on graphs.

Requested Delivery Date:  Medium priority
-->

**Comment by edwinmp** [comment]
Hi @k8hughes, this one isn't really a bug. The size of each block is determined based on the percentage it represents. In this case, the text is more than the percentage size can show. You can either hover it to see the whole text, or click on it to expand the block. All the blank blocks also have text in them but are too small for the text to show.

**Comment by k8hughes** [comment]
Is there a cleaner way of showing it?  To me is looks like a bug because you see half a line of text.  

As a user I would prefer only to see what fits the box and then hover over for full text.  What do you think?  I don't mind if you think that this should stay the way it is.  It is certainly very low priority is this is what you expected it to do.

**Comment by edwinmp** [comment]
@k8hughes, I'm closing this one. Can't figure out any way to fix it since it's coming from the map library we're using. For now, think we'll be fine with having the user click on the box to see full text :)
