### ISSUE TITLE
Hover over boxes going outside the margins of a chart.

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#355]
## i’m submitting a bug

**describe the issue**
When hovering over the boxes on information on revenue and grants 2015, the cursor moves and highlights certain boxes as it moves. But when it gets to the edge of the box you can't see it anymore. It gets hidden.

**to reproduce**
Go to ‘profiles’
Go to ‘country profiles’
Go  to ‘type country name’
Click Afghanistan 
Go to jump to country finances
Will display revenue and grants 
Keep one of the criteria to constant 2015 USD
Drag your mouse over the blue boxes of information, and up until the edge of the box
The error is there

**Expected behaviour**
To see all of the text no matter if it's near the edge of the infographic

**Screenshots/GIF**
![gif1](https://user-images.githubusercontent.com/36768381/43314736-c14c1c4c-918b-11e8-9bd1-9bf4dc1d4508.gif)

**Desktop (please complete the following information):**
 - OS: iOS 10.13.6
 - Browser Firefox

**Environment/Server:**
<pre><code>
- [ x] Production
- [ ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**
There are many instances where the bubble with info will go outside of the margins of a graphic or chart and thus become unreadable.

Requested Delivery Date: Medium priority

**Comment by edwinmp** [comment]
Hi @k8hughes... Fixed on staging.

**Comment by edwinmp** [comment]
Fixed!
