### ISSUE TITLE
Missing chart on multilateral profiles if using firefox

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#358]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[ x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
When accessing the multilateral profiles using firefox the first chart does not show.  On crome it is working as intended.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Click on profiles
2. Underneath click on multilateral profiles
3. Click on the Asia Development Bank link
4.  ODA / OOF chart is missing

**Expected Behaviour**
There should be a chart here, not just the key.

**Screenshots/GIF**
![screen shot 2018-07-27 at 12 46 29](https://user-images.githubusercontent.com/36768381/43319531-057d9b0a-919d-11e8-92d2-c524c5c101a2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS 10.13.6
 - Browser [e.g. chrome, safari] Firefox

**Environment/Server:**
<pre><code>
- [ x] Production
- [ ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: Medium priority

**Comment by edwinmp** [comment]
Hi @k8hughes ... This should be fixed both on staging and production.
