### ISSUE TITLE
Hamburger menu doesn't work on ipad view.

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#359]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[ x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
On ipad view, or just a reduced screen size the menu becomes a hamburger menu, however when you click on it is doesn't expand, therefore you cann't access any of the different areas of the DDH.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Resize screen till top level menu becomes a hamburger menu
2. Click on hamburger menu to expand
3. Nothing opens

**Expected Behaviour**
Hamberger should expand to show the top level menu allowing the user to click around and explore the DDH.

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: iOS 10.13.6
 - Browser Firefox

**Environment/Server:**
<pre><code>
- [ x] Production
- [ ] Staging
- [ ] Test
- [ ] Development
</code></pre>

Requested Delivery Date: Medium priority

**Comment by k8hughes** [comment]
When testing this i noticed that another bug.  It might be related, it might need its own issue, let me know which you prefer.

**Describe the Issue**
If a country information bubble is open before click on the hamberger menu it stays open and sits on top of the hamberger menu, obscuring it.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Hover over a country
2. Expand hamberger menu
3. Country info bubble sits on top of the hamberger
   
**Expected Behaviour**
Clicking to expand the hamberger menu should cause the country info bubble to close.

**Comment by edwinmp** [comment]
@k8hughes Fixed.

**Comment by k8hughes** [comment]
LGTM.
