### ISSUE TITLE
Bug on Government financing country profiles

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#360]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A clear and concise description of what the issue is.

The line chart to the left of of the boxburst should have the veritical axis showing negatives as well as positives, in the case when negative values are part of the trends.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
Go to 'Country profiles'
Click on 'A country profile'
Scroll down to 'Government revenue, financing and expenditure'
See error

**Expected Behaviour**
The line chart to the left of of the boxburst should have the veritical axis showing negatives as well as positives, in the case when negative values are part of the trends.

**Screenshots/GIF**

![image](https://user-images.githubusercontent.com/13347058/43533010-b3982bda-95ab-11e8-8eb9-768af87a9402.png)

**Desktop (please complete the following information):**

Chrome

**Environment/Server:**
<pre><code>
- [X] Production
- [X] Staging
- [ ] Test
- [ ] Development
</code></pre>

Requested Delivery Date: 22-08-2018

**Comment by edwinmp** [comment]
Hi @Duncan-Knox, this should be fixed on staging.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp, thank you and excellent. Confirmed that the fix has gone through fine on staging.
