### ISSUE TITLE
Canada PDF download has several missing charts

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#362]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[ x ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A clear and concise description of what the issue is.
The Canada PDF download has several missing charts.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to profiles page:  http://data.devinit.org/country-profiles 
2. Type Canada
3. Select " download and print" to access the PDF profile

**Expected Behaviour**
I expected a sheet with the same info available in the graphs and charts on the country page, instead several of the charts are broken.  Page 1 has no data on two of the charts, page 3 has lost the bottom chart, page 4 has issues on both charts.

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS 10.13.6
 - Browser [e.g. chrome, safari] Firefox

**Environment/Server:**
<pre><code>
- [ x] Production
- [ ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**

Priority medium...
-->

**Comment by edwinmp** [comment]
@k8hughes Moving this to blocked since I still can't figure out how the PDFs are generated. Will consult Cecilia.

**Comment by k8hughes** [comment]
@akmiller01 probably is a fountain of wisdom on this point as well.  
Do you know anything that could help us?

**Comment by akmiller01** [comment]
Investigating now. Could we replace it with the previous version in the meantime? https://github.com/devinit/pdf-prints/blob/b6db1e16fb15b8b38cfecbb8e3f399200c488579/20170331/Canada.pdf

**Comment by k8hughes** [comment]
Canada is fixed.  There are some other pdf bugs which I will open issues for.

LGTM.
