### ISSUE TITLE
Feature request: years to include for Global picture poverty data series.

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#363]
**Is your feature request related to a problem? Please describe.**
The problem is gaps in poverty data trends on the Global Picture, where data is available once every set number of years. Resulting in the Global picture changing between having data and having no data over a trend series. One solution to this is to have the slider only have the years with data for these indicators.

Therefore, I was wondering how complex it would be to remove certain years from showing across some of these specific indicators on the poverty tab on the Global Picture. This would be a case of years to show data for being provided and others being removed from the slider. e.g. show 2000, 2003, 2006, 2011, 2012, 2013, etc. Is this a time consuming fix?

**Describe the solution you'd like**
If this is a feasible fix then I'd supply to years to include for certain indicators and these would be the years available on the slider. We might need a further text fix on the page to highlight why the slider is set up to show data for every few years as opposed to every year. A further layer of complexity may see the slider reference each year being shown along it, however this is probably too time consuming to fix?

**Describe alternatives you've considered**
The following are in motion depending on the indicator and staging/live:
- Interpolation of data where the gaps are filled with estimates
- Leaving as it with "no data" showing in the gap years
- Colouring the "no data" with the same colour as the last year with data, still showing tool-tip as "no data"

**Additional context**

**Requested Delivery Date:** Ideally looked into before poverty series on global picture pushed live.

**Comment by Duncan-Knox** [comment]
@edwinmp I'd suggest this is a higher priority feature request compared to others on the Kanban, for instance compared to issues 361 (https://github.com/devinit/datahub/issues/361) and 351 (https://github.com/devinit/datahub/issues/351). Is it possible to swap this into the to do list? Happy to discuss if needed, we'll need to select which Global Picture indicators to apply this too, it is only relevant for a small number and not all.

**Comment by edwinmp** [comment]
@Duncan-Knox, this isn't possible at the moment, probably not at all. Not without changing this to a different widget, not a slider. Perhaps a drop-down.
Also, I don't find it to be a problem. It's honest, showing a "no data" map for years with no data. Finding gaps may seem more like a bug.

**Comment by Duncan-Knox** [comment]
@edwinmp definitely would not advise changing to a drop-down. I agree with your points on the "no data" aspect however am not certain if others would. I'll aim to check. Happy to discuss at a later stage. I also wonder what would happen if the data was submitted without certain years included, might this result in the slider only picking them up, or is it hard coded to have every year in no matter what is in the data?

**Comment by edwinmp** [comment]
@Duncan-Knox it's not hardcoded really. It's just that this particular element requires a range; so you specify the minimum & maximum value, and how many you need it to skip through while you slide it. Let me see if I can find a way around this limitation. Someone somewhere has to have needed a solution to this same problem.

**Comment by Duncan-Knox** [comment]
@edwinmp noted I understand on the range. Hopefully there can be a way around. If not then it should be fine as it is and I can prepare a note the page explaining about the data, Let's see what you find on the coding front, please keep me updated.

**Comment by Duncan-Knox** [comment]
Interpolated data has been added where available to fill gaps in years. Interpolated data is not currently available for P20 indicators. A note has therefore been added on the indicator Global Picture page explaining data availability situation by year in these cases. A request will be made for interpolated P20 data.
