### ISSUE TITLE
Domestic.csv data transformations

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#375]
Once #329 is signed-off the data is worked through on the database to allow transformations to take place. This includes conversion into US$, US$ constant prices, calculation per person data with PPP$ for per person data. These require a methodology update compared to previously done transformations. Various breakdowns made available as shown across DDH components. New changes to the set-up layers are worked through.

**Comment by Duncan-Knox** [comment]
Alex Miller has been involved in the past for these transformations.

**Comment by k8hughes** [comment]
Alex has made this repo for transformations: https://github.com/devinit/domestic_finance_2018

**Comment by Duncan-Knox** [comment]
Confirmation from Richard that this has not been signed-off.

**Comment by k8hughes** [comment]
@akmiller01 to give details of the files for the indictaors on the world map.
@laurenceford  to check on staging then handover to Richard.

**Comment by akmiller01** [comment]
All files here: https://github.com/devinit/domestic_finance_2018/tree/master/output

Besides `domestic.csv` itself, where it may be work comparing `value` (constant 2016 USD), `value.ppp` (constant 2011 PPP), and `value.ncu` (constant NCU), the following are derived from domestic and are on the world map:

- gov-revenue-percent-gdp.csv
- govt_spend_pc.csv
- grants-percent-total-revenue.csv
- non-grant-revenue-ppp-capita.csv
- total-revenue-percent-gdp.csv
- total-revenue-ppp-capita.csv

And are written with this code:

- https://github.com/devinit/domestic_finance_2018/blob/master/project_code/govrev.R
- https://github.com/devinit/domestic_finance_2018/blob/master/project_code/grants-pct.R
- https://github.com/devinit/domestic_finance_2018/blob/master/project_code/non-grant.R
- https://github.com/devinit/domestic_finance_2018/blob/master/project_code/total-expend.R
