### ISSUE TITLE
Unbundling OOFs revision to constant 2016 prices

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#391]
Should be under fact however adding a separate issue due to relative size of undertaking

**Comment by akmiller01** [comment]
Looks like `oof_2015` series was aggregated from CRS source that was already in constant 2015 https://github.com/devinit/ddh_donata_scripts/blob/6e264331d2440edfd43c2834e40c1571cc8c9fcd/data_etl/dh/fact_oecd/CREATE_TABLE_oof.sql#L216

Deflation to 2016 will take additional code...

**Comment by edwinmp** [comment]
@Duncan, what is the front-end requirement on this?

**Comment by Duncan-Knox** [comment]
It's coming through in a different price base. We'll need to check with @Napho

**Comment by Napho** [comment]
@Duncan-Knox  data should be fine now, the re-submission of p_160 is having two values per country per year, i think there was an error on your end, just double check

**Comment by Duncan-Knox** [comment]
Checked and fine, @edwinmp
