### ISSUE TITLE
App responsiveness on all device sizes

### ISSUE THREAD

**Issue by edwinmp** [devinit/datahub#392]
## I'm submitting a ...
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Currently we have;

- [x] Map text is out of bounds on smaller devices
- [x] Map legend is out of bounds on smaller devices
- [x] The text in the top and bottom ten lists is out of alignment on smaller devices
- [x] Menu toggle doesn't work

Those above are just the few clear ones. Will need a thorough test to discover more.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Open the data hub on your mobile phone
2. Scroll through and see the mess

**Expected Behaviour**
I'd love to see seamless responsiveness of the application especially on smaller device sizes (phones & tablets).

**Screenshots/GIF**
![image](https://user-images.githubusercontent.com/5672438/43938398-0a120ba4-9c6c-11e8-94b3-317e0eca8795.png)

**Desktop (please complete the following information):**
 - OS: [ALL]
 - Browser [ALL]

**Smartphone (please complete the following information):**
 - Device: [ALL]

**Environment/Server:**
<pre><code>
- [x] Production
- [x] Staging
- [ ] Test
- [ ] Development
</code></pre>

Requested Delivery Date: September 2018

**Comment by k8hughes** [comment]
![screen shot 2018-09-24 at 15 46 41](https://user-images.githubusercontent.com/36768381/45959137-168b3900-c011-11e8-9c8d-9b03825b5c76.png)

When the legend is expanded on mobile view it becomes really hard to read as it is overlapped by other elements.  The date slider for example.  The text over the map is also hard to read on mobile, would it work to move this to below the map or does it create too much scrolling?

**Comment by k8hughes** [comment]
For ipad it doesn't seem like the ability to hide the legend has worked.  This is how it looks using developer tools.
![screen shot 2018-09-24 at 15 52 29](https://user-images.githubusercontent.com/36768381/45959620-3f5ffe00-c012-11e8-8a18-f35c9ae76ab1.png)


Also as per slack discussion it would be good to add the single and double tap navigation for phone users so on one tap they see the things a desktop users see on hover over and on two taps they get what a desktop users has on click through.

**Comment by edwinmp** [comment]
Done with fixing the issues in the feedback above, except for the single/double tab mobile bit. Turned out to be a bit trickier than I expected. Will look into in this sprint.

**Comment by edwinmp** [comment]
Going to create a separate feature request for it.

**Comment by k8hughes** [comment]
Good solution to have the show / hide button.  LGTM.

**Comment by edwinmp** [comment]
Deployed!
