### ISSUE TITLE
Global Picture international official finance

### ISSUE THREAD

**Issue by Napho** [devinit/datahub#393]
This involves automated data entries for Global Picture as per content audit document. 

https://docs.google.com/spreadsheets/d/1Z4smT1G2FxiabZ-bes0PghDJCBl-5G8VggLUFCkUOL0/edit#gid=524137556

The data does not require any deflation as the tables use current prices and constant prices given by oecd. Part of this data is manually submitted, automated tables not manually submitted by Duncan are below

List of tables include 

- [x] fact.in_oda_gross_constant
    - [x] generated
    - [x] Signed-off by DK
    - [x] uploaded to staging
- [x] fact.in_oda_net_2015
    - [x] generated
    - [x] Signed-off by DK
    - [x] uploaded to staging
- [x] fact.out_oda_net_2015
    - [x] generated
    - [x] Signed-off by DK
    - [x] uploaded to staging
- [x] fact.oda_percent_gni
    - [x] generated
    - [x] Signed-off by DK
    - [x] uploaded to staging
- [x] fact.oda_to_ldcs_percent_gni
    - [x] generated
    - [x] Signed-off by DK
    - [x] uploaded to staging
- [x] fact.in_oof_gross
    - [x] generated
    - [x] Signed-off by DK
    - [x] uploaded to staging
- [x] fact.out_oof_net
    - [x] generated
    - [x] Signed-off by DK
    - [x] uploaded to staging
- [x] fact.out_ssc_net
    - [x] generated
    - [x] Signed-off by DK
    - [x] uploaded to staging
- [x] fact.ssc_percent_gni
    - [x] generated
    - [x] Signed-off by DK
    - [x] uploaded to staging

**Comment by Duncan-Knox** [comment]
@Napho you do not need to do ODA to LDCs percent GNI this is finished. I'll aim to speak to you today about some of the others.

**Comment by Napho** [comment]
I have negative values in generated files, not sure if this is correct, Duncan will have to double check and confirm, the files will be uploaded to drop box for him to do checks on, more documented process for these file generations will be attached here based on final reviews from Duncan

**Comment by Duncan-Knox** [comment]
Depends which indicators and how frequently the negatives are occurring @Napho. I'd expect the vast majority to be positive. I'll check into it.

**Comment by Duncan-Knox** [comment]
Name changes being made to replace 2015 with constant.

**Comment by k8hughes** [comment]
This is so close to being finished it is really great!

**Comment by edwinmp** [comment]
@Duncan-Knox, could you list the visualisations each will affect so we can test and see if the complete ones are coming through on staging.
If there's been any name changes, need to make the necessary CMS changes to pull those through as well.

**Comment by edwinmp** [comment]
Very nice... thanks @Duncan-Knox

**Comment by edwinmp** [comment]
@Duncan-Knox There's the one for the unbundling oof ... `fact.oof_2015`. Not sure if that's done or not, but the visualisation is failing on staging and will likely stall the release if it's still on going. Actually suggest that the table name updates be done last, after the table data has been updated. If possible.

**Comment by Duncan-Knox** [comment]
@edwinmp this one was not reflected here as this was referring to specific parts of the Global Picture. However, fact.oof_2015 has been updated to fact.oof_constant here: https://github.com/devinit/datahub-cms/blob/development/unbundling-oof/concept.csv. I'll continue to edit the table above to reflect any further name changes and make sure these are done on the CMS.
