### ISSUE TITLE
Unbundling OOFs is showing no data

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#409]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'Other visualisations'
2. Click on 'Unbundling OOFs'
3. Click on 'Explore'

**Expected Behaviour**
US$ values should show

Requested Delivery Date: 15/09/2018

**Comment by edwinmp** [comment]
Hi @Duncan-Knox @Napho  ... this is accompanied by error in the image below ... could probably mean something to you (the part about the missing relation); haven't looked deeper yet.

![image](https://user-images.githubusercontent.com/5672438/44786064-a1584f80-ab9b-11e8-847b-8a97a448ed7d.png)

**Comment by Duncan-Knox** [comment]
Ok thanks @edwinmp. It looks like it has disappeared from database.

**Comment by edwinmp** [comment]
@Napho Query is `SELECT to_di_id, year, sum(value) AS value from fact.oof_2015 WHERE value > 0 AND year = 2016 GROUP BY to_di_id, year`

**Comment by edwinmp** [comment]
@Duncan-Knox This should be fixed on the live server, but we can leave it up till it's fine on staging as well.

**Comment by Duncan-Knox** [comment]
Thanks @edwinmp this works well. Live fix has gone through fine.
