### ISSUE TITLE
Track more areas on the DDH to improve google analytics

### ISSUE THREAD

**Issue by edwinmp** [devinit/datahub#418]
**Is your feature request related to a problem? Please describe.**
Google analytics on the site are not as detailed as we'd like them to be. Current tracking doesn't provide a clear enough picture on user activity.

**Describe the solution you'd like**
Add tracking to the following areas on the site:
- [x] Map indicators
- [x] All downloads
- [x] Share and social media buttons

**Requested Delivery Date:** This sprint

**Comment by edwinmp** [comment]
NB: May also need to track hits that originate from shared links.
https://stackoverflow.com/questions/37570823/how-to-filter-by-query-string-in-google-analytics

**Comment by k8hughes** [comment]
Are there any notes we need to leave our future selves about how you did what you did?

I've chatted with James, he is happy with the changes but wants to run it by Anna before giving the final LGTM.

**Comment by edwinmp** [comment]
Links to the commits. Should be adding the issue number in the commit message. GitHub automatically attaches the commit to the issue when you do that.

- To [track indicator views ](https://github.com/devinit/datahub/commit/fcb9cee94b5e50bdac991d85f384d613f284e8c4)
- To [track downloads](https://github.com/devinit/datahub/commit/7a477522f9e02a15c67488183d56b34308a6901e)
- To [track social links and PDF downloads](https://github.com/devinit/datahub/commit/c6e7044ceb0421fc7a5c53e2d3de1b26c487ee2a)
