### ISSUE TITLE
Check whether Domestic Data Update causes errors on frontend visualisations

### ISSUE THREAD

**Issue by akmiller01** [devinit/datahub#420]
Richard has suggested that when the sum of the children of a parent item in domestic.csv do not add up to the value of the parent, this can cause bugs in the visualisations. Presumably he's talking about the "boxburst" visual, the only one that uses domestic.csv directly.

Prior to uploading the new domestic.csv data entirely, we should test whether it creates errors, and address it either by changing the data in transformation, or by editing the visualisation code.

We should be able to test this as soon as needed, given the domestic.csv and domestic-budget-levels.csv available here: https://github.com/devinit/domestic_finance_2018/tree/master/output They do not contain the full list of countries, but they have the majority of them.

**Comment by Duncan-Knox** [comment]
CMS edits for government finance data

**Comment by k8hughes** [comment]
@laurenceford and I will check through every country - our testing spreadsheet is here:  https://docs.google.com/spreadsheets/d/1mRUjA4__W0880auox245rQZ1s_ufGhBNc2VWn60o1GI/edit#gid=0
