### ISSUE TITLE
Change where a user starts on the global picture

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#422]
**Is your feature request related to a problem? Please describe.**
When you first view the data hub the first global picture visualisation only has data p to 2013.  This gives a bad impression of the bredth of data we supply.

**Describe the solution you'd like**
As a user I'd like to first land on a tab that shows more surrent data.  I'd also like to have an explaination in the text on that visulation that tell my why the data only goes up to 2013.  

**Describe alternatives you've considered**

**Additional context**
The order of tabs of the global picture wasn't well thought through at conception so we do not need to keep things in the current order if we don't want to.
This is the part of the global picture we want users to see first:  http://data.devinit.org/global-picture/international-official-finance 
We will need @Duncan-Knox to give the detail for the copy change on the page.

**Requested Delivery Date:** dd/MMM/YYYY

In time for ITEP launch so we've improved this part of the user experience when we are promoting the hub lots.

**Comment by k8hughes** [comment]
Excellent, nice one Edwin!
LGTM.

**Comment by edwinmp** [comment]
Deployed!
