### ISSUE TITLE
Turkey missing component

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#430]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[ ] Bug report 
[ x] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Turkey is now missing the overview component

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to http://212.111.41.68:8080/country/turkey

3. Scroll down to "overview"

**Expected Behaviour**
"React component has an error! " is the error message

**Screenshots/GIF**
![screen shot 2018-10-04 at 14 47 33](https://user-images.githubusercontent.com/36768381/46480151-8d31ee80-c7e8-11e8-804e-d60cca2c5c9a.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser Mozila

**Environment/Server:**
<pre><code>
- [ ] Production
- [ x] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: 08/10/2018

**Comment by k8hughes** [comment]
Interestingly there is the same error for South Africa:  http://212.111.41.68:8080/country/south-africa

**Comment by Duncan-Knox** [comment]
This has been fixed with the updates to the CMS file for government finance layers.

**Comment by edwinmp** [comment]
I'm marking this LGTM. Thanks for the fix @akmiller01.

**Comment by edwinmp** [comment]
Deployed!
