### ISSUE TITLE
Pakistan expeniture box burst graphic has disappeared

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#434]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[ ] Bug report 
[ x] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Pakistan expenditure box burst graphic has disappeared

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to http://212.111.41.68:8080/country/pakistan 
2. Click on Government Finance
3. Scroll down to the Expenditure section at the bottom

**Expected Behaviour**
On live there is a box burst graph below

**Screenshots/GIF**
![screen shot 2018-10-04 at 17 14 58](https://user-images.githubusercontent.com/36768381/46488105-aabb8400-c7f9-11e8-867f-1822b2ee8268.png)

**Desktop (please complete the following information):**
 - OS: 
 - Mozila

**Environment/Server:**
<pre><code>
- [ ] Production
- [x ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**
This is a lower importance bug for launch, we can launch with it and fix after

Requested Delivery Date: dd/MMM/YYYY

**Comment by edwinmp** [comment]
@Duncan-Knox  I think this one may be related to issue #344. I don't know what's changed in the data to bring rise to this. Error is below 
![image](https://user-images.githubusercontent.com/5672438/46609631-45290980-cb11-11e8-87cb-b475865f62ab.png)

I think there's some inconsistencies with the Pakistan expenditure tree that my earlier fix has failed to compensate for. Maybe @Napho can have a look.

**Comment by Duncan-Knox** [comment]
@edwinmp I see this one does not reference the react component and the visual straight out disappears. Other than that it looks the same as #344. It is completely unclear to me what is causing this. Do you have any idea on the type of inconsistencies? I'll show Richard the data in the case he can spot something too.

**Comment by Duncan-Knox** [comment]
@edwinmp update: this links to negative values in the government expenditure data used in the treemaps. Richard will remove these and resend the data to @akmiller01 for another upload. This ought to fix it.

**Comment by akmiller01** [comment]
Further research has led me to conclude that when the partition treemap was refactored into the `charts` repo, the negative logic was accidentally excluded. In the Datahub-angular repo I found logic that took the absolute value of a child node https://github.com/devinit/datahub-angular/blob/master/public/diConcept/components/PartitionTree/partitionTreeDirective.js#L221 and assigned a blue/red value depending on if it was once negative https://github.com/devinit/datahub-angular/blob/master/public/diConcept/components/PartitionTree/partitionTreeDirective.js#L261-L265

I think we'll need to fit the negative/absolute value logic into charts/core/src/datasets where it creates the partition tree data https://github.com/devinit/charts/blob/master/packages/core/src/dataset/index.ts#L42

**Comment by akmiller01** [comment]
Alternatively, since the error seems to be stemming from `stratify` it might be getting confused when children and parents have the same ID 
![image](https://user-images.githubusercontent.com/2836840/46878444-54f66580-ce11-11e8-8602-bd36cc4c94d7.png)

**Comment by akmiller01** [comment]
And in the case of Brazil, it's because the parent has a 0 value while the child is negative. I might need to try fixing my level-fixing script... 
![image](https://user-images.githubusercontent.com/2836840/46878706-f2519980-ce11-11e8-86fc-68f89646a0b2.png)

**Comment by akmiller01** [comment]
@Napho and @edwinmp , Richard provided me a few data fixes that might help avoid these issues. If you pull the latest output from the `domestic_finance_2018` branch, it may fix this problem.

**Comment by Duncan-Knox** [comment]
Bug fixed in data @edwinmp , no front-end work required, besides pulling through new data.
