### ISSUE TITLE
Government Finance x axis intervals not consistent

### ISSUE THREAD

**Issue by laurenceford** [devinit/datahub#437]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
X axis year interval labels are inconsistent, e.g. 2007, 2010, but then no further labels (despite the fact that data goes up to 2016)

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to DRC country profile
2. Scroll down to the government revenue charts

**Expected Behaviour**
X axis year intervals should be consistent e.g. every 3 years

**Screenshots/GIF**
DRC:
![image](https://user-images.githubusercontent.com/39994548/46527229-7fcc4100-c888-11e8-9d0b-fc06b7349086.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome

**Environment/Server:**
<pre><code>
- [ ] Production
- [x] Staging
- [ ] Test
- [ ] Development
</code></pre>

Requested Delivery Date: 08/10/2018

**Comment by edwinmp** [comment]
It seems the chart is terrible at handling odd date ranges (in this case, 2007 - 2016). Best I could do was make determining these steps dynamic. So now the gap can be either 3, 4, or 5 years. So if you see that, it's not a bug :)
