### ISSUE TITLE
Bug on government finance data on recipient digital profiles

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#440]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Banner on recipient profiles under the overview, the 'what resources are available' 'Domestic Public' section shows as 'no data' in some cases where there should be data. Alex picked up that this is likely because of a setting where it only takes domestic data is if it is budget type of 'actual' as opposed to projected. This is also an issue on the 'government finance' section of the banner.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'a recipient profile e.g. Chile'
2. Click on 'Overview' or 'government finance'
3. See error

**Expected Behaviour**
Data should show for projected data in 2016 in the case that actual is not available, as opposed to stating 'no data'.

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

![image](https://user-images.githubusercontent.com/13347058/46599194-7fc57e80-cade-11e8-96e5-c8c313965741.png)

![image](https://user-images.githubusercontent.com/13347058/46599206-894ee680-cade-11e8-98ba-72d111dd6537.png)

**Environment/Server:**
<pre><code>
- [X] Production
- [X] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date:

**Comment by edwinmp** [comment]
@Duncan-Knox, just to clarify... is this just for those two tabs (overview & government finance), or do I support projected data all through (in favour of 'No data available')?

**Comment by Duncan-Knox** [comment]
I believe outside of the PDFs, that is only in these two tabs where this is relevant. Have you seen this occur elsewhere?

**Comment by edwinmp** [comment]
@Duncan-Knox ... Have deployed this. Please have a look.

**Comment by Duncan-Knox** [comment]
Thank you @edwinmp the fix looks good.
