### ISSUE TITLE
Late removals on government finance data

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#441]
Proposing the following for the launch:

Please remove data for the following indicators under government finance on the global picture, for South Sudan, for 2017, 2018:

data_series.non_grant_revenue_ppp_pc
data_series.total_revenue_ppp_pc
data_series.government_spending_pc

**Comment by Duncan-Knox** [comment]
And @akmiller01 @Napho the removal to be done on domestic.csv for South Sudan in 2016 and 2017.

**Comment by akmiller01** [comment]
https://github.com/devinit/domestic_finance_2018/commit/09f4f61b4a726f09b7c1423eeda6cfb57500dda5 Pushed to master. Will work on domestic.csv now.

**Comment by akmiller01** [comment]
Done, in master @Napho https://github.com/devinit/domestic_finance_2018/commit/cf78f434cdf1978820a040194aea65eb58e2ea9c
