### ISSUE TITLE
Missing government finance data for certain countries

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#449]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Missing data for government financing tab for Syria, Somalia and West Bank and Gaza Strip. Unclear what is causing this and may be a joint point to look into @elmetodo, @akmiller01, @edwinmp. The CMS file was updated to mark these countries as having domestic data.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'Digital country profile'
2. Click on 'Government finance'
3. See error

**Expected Behaviour**
These should show data for government finance. In the case of Syria this will be historical.

**Screenshots/GIF**
Syria:
If applicable, add screenshots or a GIF to help explain your problem.
![image](https://user-images.githubusercontent.com/13347058/47018102-ec2e2680-d14b-11e8-8324-c74a8a2f70a5.png)

Somalia:
![image](https://user-images.githubusercontent.com/13347058/47018127-fd773300-d14b-11e8-8d95-f67c2c1abb8f.png)

West Bank and Gaza Strip:
![image](https://user-images.githubusercontent.com/13347058/47018164-0ff16c80-d14c-11e8-9fee-af1b37c19d0d.png)

**Additional Context**
Unclear what is causing this: may need front-end or back-end debugging work.

Requested Delivery Date: mid-high level importance

**Comment by akmiller01** [comment]
It does not look like West Bank/Palestine has domestic data at all @Duncan-Knox .

For Syria and Somalia, they do not have USD or PPP exchange rates, so all of their data is in NCU.

Graphql data is being pulled from this line https://github.com/devinit/datahub-api/blob/master/src/modules/dw/CountryProfile/sql.ts#L5 So the `value is NOT NULL` query drops Syria and Somalia. If we want just their NCU data to show, we'll need to change the `value is NOT NULL` query to `value_ncu is NOT NULL` @edwinmp and ensure that the Front-End Country Profiles can automatically toggle to NCU in the event of a valid NCU but no valid USD/PPP.

**Comment by edwinmp** [comment]
@Duncan-Knox, shouldn't this be related to issue #433? Cos I added the "fix" in the screenshots as the FE handler for these no data situations, originating with this Panama issue.

**Comment by Duncan-Knox** [comment]
@akmiller01 great spots on those without USD or PPP exchange rates. Now I recall @elmetodo had said the data for West Bank and Gaza Strip had fallen off the file, I'll remove it as having domestic data until/if it is re-added to the master file.

**Comment by Duncan-Knox** [comment]
@edwinmp I don't these would share the same root cause. We now know the cause of the three listed in this issue. West Bank and Gaza Strip has no data for government finance so I will re-edit the CMS so it is not shown. Somalia and Syria have government finance data but no transformation data to show it in US$. Hence the comment from @akmiller01 on the NCU toggle option here.

**Comment by edwinmp** [comment]
@Duncan-Knox can't find country profiles for West Bank and Gaza Strip. Could you get me the links. Thanks.

**Comment by edwinmp** [comment]
@Duncan-Knox @akmiller01 this one required changes across three repos. Added an option in the CMS [here](https://github.com/devinit/datahub-cms/commit/dd88f36f883a6ec57547ec1b3d0df692956b89e8) in the `currency.csv`. Still need to fix the formatting for that but as you can see, that new option allows to toggle support for both local & USD or just local.
For any other countries with this problem, please set this option to `true` (only tested with Syria).

**Comment by edwinmp** [comment]
Commit List:
https://github.com/devinit/datahub-api/commit/ddfe84d42b144f079ea4761211b9df55b1c375c0
https://github.com/devinit/datahub-api/commit/a3a8a6009ca15aa223e6fc7b62472e07d8de6572
https://github.com/devinit/datahub-cms/commit/dd88f36f883a6ec57547ec1b3d0df692956b89e8

**Comment by akmiller01** [comment]
@edwinmp West Bank is called Palestine on the Datahub: http://data.devinit.org/country/palestine

**Comment by akmiller01** [comment]
This would need a fix in reference.di_currency. Last update we probably got Somali data in USD.

**Comment by Duncan-Knox** [comment]
Sounds ok this is what you have in the update, unless this causes other issues
