### ISSUE TITLE
Determine user needs for a Datahub API

### ISSUE THREAD

**Issue by akmiller01** [devinit/datahub#450]
If we can determine user needs for an API, we can determine whether our GraphQL backend is already fit for purpose, or if we need to build an additional interface. Some questions to ask of users to determine whether GraphQL will work:

1. What output formats can you work with? What output formats are not useful to you?
2. Can you handle hierarchical data, or does output need to be flattened for you?
3. Can you POST your queries, or does GET need to be supported as well?
4. Can you write queries for the request if the query format is properly documented?
5. Which datasets of ours are you most likely to want to download, and how often?
6. Can you join meta-data to your output, or do you need it pre-joined? (e.g. country names to IDs)

Any more questions we can think of?

**Comment by akmiller01** [comment]
At present, GraphQL requires some coding to access. It's not as simple as typing a URL into a web browser and getting a CSV download as an output. It requires a POST request with a formatted query, and returns JSON that needs parsing (simple coding tasks, but almost impossible without coding).

However, if our users require CSV outputs, they can download our data on the `methodology page` and don't need to bother with an API at all.

Maybe we could show our users who have requested API access the documentation I've done so far here https://github.com/devinit/datahub-api-documentation and ask them if they can use the R or Python scripts.

**Comment by edwinmp** [comment]
@akmiller01 you'll find a list of the officially supported languages (with libraries) [here](https://graphql.org/code/). I don't think there's any API that doesn't require coding to access. Most API services provide an interface to test their API out, but fortunately, `graphql` provides one for every endpoint.
The whole point of the API is that we shall provide developers with an easy way to access our data for the specific purpose of building their own tools based on it, be it simple visualisations or full apps. It's not for analysts. If we're to build a UI for viewing our DDW data & maybe even exporting it in different file formats, that could be a more valuable resource for analysts.

**Comment by akmiller01** [comment]
Definitely agree @edwinmp. This is why it's important to actually understand what the user needs are. If I was an external user, I'd be more than satisfied with GraphQL as an API interface to the DDH, but our users might be expecting something more like a UI where they have an interface where they can build a query that spits out an XLSX.

This also begs an interesting question, if other developers do want to build tools off of our API, we might want to specify how we want to be cited on their websites.

**Comment by edwinmp** [comment]
I think we can accommodate both the GraphQL & the UI to cater for the disparate group of users and their needs. Though I'm not totally convinced we need the UI version ... seems like more work than we need since the output of a `GraphQL` query can be programatically pursed and output as a CSV. I'd be more inclined to add detailed documentation of how to do this in the different languages.

I think the first question is "Who are our users?"

**Comment by k8hughes** [comment]
How do we use other people's data API's? 
This could answer some of our questions.  If we think how we use an API from the world bank or someone similar this could be a good starting point.

**Comment by akmiller01** [comment]
For the World Bank, there's a pre-written R package that I use to connect to their API and download indicators https://cran.r-project.org/web/packages/WDI/WDI.pdf I don't know if any other staff at DI make use of any other API...

**Comment by Napho** [comment]
A lot of my past works has been API work, but most of the service or content providers give libraries which is more like what World Bank did, personally i just prefer a proper documentation with a standard architectural style, either xml over RPC, xml over Http, SOAP or RESTful service. Its alot easier to work and gives more flexibility. In our case i guess adding an authentication layer on top of the current Graphql implementation would work

**Comment by akmiller01** [comment]
Start on an API here: https://github.com/devinit/ddw-external-api

After a discussion with Bill, there's a few more points to be addressed.

1. Better meta-data. Right now the API cannot access the `public` schema (probably due to internal schema rules). But it's hard to tell whether sufficient metadata exists for users to lookup variable names.
2. Fit-for-purpose for data download for users. If they're on a country profile, how can they download all the data on the profile? Right now it would be joining like 20 tables. Could this be done with a View @Napho ?
3. Make sure, if we do have big views, it isn't a substantial drain on the DB. Could we do caching?

**Comment by edwinmp** [comment]
@akmiller01 on the security side, there's also preventing attacks that aim to overwork the system. Usually this is handled by limiting the number of requests per second from a single source.

**Comment by akmiller01** [comment]
Good point, @edwinmp. I generally try and steer clear of access tokens because they can be a barrier to use for developers, but maybe we could implement something like this? https://www.npmjs.com/package/ddos

**Comment by k8hughes** [comment]
Coping from slack so the convo isn't lost in time.  Not sure if this is the right place to track it but it is better than slack at least!

@akmiller01  says:  I had some spare time and decided to implement `/meta_data` and `/multi_table` endpoints into the API. 
I think this should fulfill @Bill's requirements for a query that could fetch all the Country profile indicators for a single country. But again we'd need to evaluate how this will impact the DB (it's technically running n+1 separate queries against the DB, where n is the number of indicators)
And it will probably break if the data structure between two indicators in the query are too different (requesting SOU and map data in the same query). But it allows for some flexibility in columns.
Here's an example query I put together with two indicators for Uganda at once: http://212.111.41.68:8000/multi_table?indicators=population_total,govt_revenue_pc_gdp&entities=UG&start_year=2015&format=xml
And as usual, I wrote a little bit of documentation here: http://212.111.41.68:8000/
Oh, and for @edwinmp , I also implemented that `ddos` node package. So at the very least people who spam queries in a malicious way will be rate-limited.

Yeah, mixing entities does not work: http://212.111.41.68:8000/multi_table?indicators=population_total,uganda_agri_percent&entities=UG,d101&start_year=2015&format=xml

But within SOU, you can mix indicators: http://212.111.41.68:8000/multi_table?indicators=uganda_primary_sit_write,uganda_primary_enrol&entities=UG,d101&start_year=2015&format=xml

**Comment by k8hughes** [comment]
@Napho to look at this an suggest improvements.

**Comment by k8hughes** [comment]
@akmiller01 can we rename the API so it says DDH not DDW?

**Comment by edwinmp** [comment]
@k8hughes, we can rename it, but it'd not be accurate as DDH. The DDH represents a small part of the DDW, and this API grants access to the DDW beyond what's on the DDH.

**Comment by k8hughes** [comment]
I think the plan for step one is only to allow users to the data that is on the DDH not the entirity of data on the DDW, so we should definately have a discussion about this aspect of the API when everyone is back after the holidays.

**Comment by Napho** [comment]
The schema spotlight_on_kenya is not used in ddh, there should be no reference to it. Only spotlight_on_kenay_2017

**Comment by k8hughes** [comment]
Has the spotlight data issue been resolved? @akmiller01 @edwinmp can we close this issue now?

**Comment by edwinmp** [comment]
@Napho the implementation ignore schemas and pretty much searches through the entire warehouse for the matching table, based on indicator. So if there's a duplicate table name across schemas, there'll be trouble.

@k8hughes still happening.

**Comment by akmiller01** [comment]
@edwinmp , I think the Spotlight issue is resolved: http://212.111.41.68:8000/single_table?indicator=kenya_poverty_meanpp_exp&format=json

**Comment by akmiller01** [comment]
I think we're done with user needs on the API. Any remaining concerns about it fall into the dev needs category...
