### ISSUE TITLE
Areas of site that appear to be hyperlinks are not

### ISSUE THREAD

**Issue by jamesharle** [devinit/datahub#455]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Many areas of the site which appear to be hyperlinks are not, and clicking on them only triggers the drop-down menu in use to close. This includes the country profiles list.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'http://data.devinit.org/country-profiles'
2. Click on 'the 'type a country name' box'
3. Click on any area that is not actually text

**Expected Behaviour**
Any area that is a hyperlink should be visible as such and redirect when clicked. Any area that is not a hyperlink should not appear to be such, and should not trigger any behaviour when clicked.

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Chrome]
 - Version [69.0.3497.100]

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by edwinmp** [comment]
@jamesharle Besides the one on the country profile page, I also fixed the menu items. You can verify on staging. Let me know if you've found any others. This was a good catch. Thanks @jamesharle .
