### ISSUE TITLE
American spellings

### ISSUE THREAD

**Issue by jamesharle** [devinit/datahub#456]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
American spellings are sometimes used on the DDH. A prominent example is the 'using this visualization' button on each page. These should read 'using this visualisation'.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to '**http://data.devinit.org**'
2. See error

**Expected Behaviour**
A clear and concise description of what you expected to happen

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by edwinmp** [comment]
Hi @jamesharle ... fixed the ones mentioned above, and some I encountered while updating Spotlight on Kenya. You can have a look on staging http://212.111.41.68:8080. Will leave this open till we're sure we've exhausted all of them. Please let me know if you encounter more. Will keep an eye out as well :)
