### ISSUE TITLE
Updating the Poverty and P20 visuals on the recipient digital profiles

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#460]
The new poverty data is capturing a new year of data, please could this change be reflected on three visualisations on the recipient profiles digital banner. I believe the control for changing years are hard-coded and not possible to change via the CMS. We now have poverty data available up to 2015.

The following front-end changes on recipient digital profiles should be made @edwinmp for this update. 

Under **Overview:**
![image](https://user-images.githubusercontent.com/13347058/49508081-bc60ec80-f879-11e8-9290-cbc0e9a1c69c.png)

HOW MANY OF THE POOREST PEOPLE GLOBALLY LIVE IN XXXX?
- Change poverty data to show for 2015
- Change population data to show for 2015
- Change info for info 'i' to state 'Data is for 2015'
- Remove reference to factsheet on info 'i' - 'See our factsheet: http://devinit.org/wp-content/uploads/2015/03/Factsheet-Ending-poverty-by-focusing-on-the-poorest-20-percent-of-people-globally.pdf.'

Under **Poverty:**
![image](https://user-images.githubusercontent.com/13347058/49508124-d7cbf780-f879-11e8-9762-fe135c00ce74.png)

IS POVERTY REDUCING OVER TIME?
- To edit years to show data from 2000-2015 on visual.

HOW DEEP IS POVERTY?
- To edit year to show data for 2015 on visual and on info 'i' note to state 'Data is for 2015'.

**Comment by edwinmp** [comment]
Hi @Duncan-Knox, majority of the issues above could be fixed with a CMS change. Refer to this commit.
https://github.com/devinit/datahub-cms/commit/5bc844626917959a7eee9313e9b9e669af67f2ef

**Comment by Duncan-Knox** [comment]
Hi @edwinmp noted for future on the CMS changes bring possible for these visuals, apologies I missed it this time round. As said data_series.poorest_20_percent will now need updating and submitting into the data warehouse. We will notify you once this stage has been completed.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp the data updates and metadata changes raised in this issue have gone onto the staging page successfully and are ready to go on live at the next convenient time for you to load these on.

**Comment by edwinmp** [comment]
Hi @Duncan-Knox, could you please check whether this is done?

**Comment by Duncan-Knox** [comment]
Hi @edwinmp Thank you for the post.  I have checked this on live at it is showing fine.

**Comment by edwinmp** [comment]
Great... closing.
