### ISSUE TITLE
Vulnerability to two decimal places

### ISSUE THREAD

**Issue by laurenceford** [devinit/datahub#473]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Data in the global picture for Vulnerability - Climate Change to read to two decimal places

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requested Delivery Date:** 19/12/2018

**Comment by edwinmp** [comment]
@laurenceford this is done and deployed to live.
