### ISSUE TITLE
Colours for country profile population graphics

### ISSUE THREAD

**Issue by jamesharle** [devinit/datahub#477]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
The Urban Vs Rural and age profile graphics, located under the population tab of Country Profiles, is off-brand. Specifically, we need the green #b7c100 changed to the dark red #8f1b13; and the blue #0095cb changed to the light red #f0826d. These changes will apply to the blue text as well as the graphics.
**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to any country profile
2. Click on the 'population' tab.

**Expected Behaviour**
We'd like this to be on brand.

**Screenshots/GIF**
![image](https://user-images.githubusercontent.com/43270042/50282219-f3262d80-0449-11e9-9b0c-0b227005bc41.png)

**Desktop (please complete the following information):**
 - OS: [windows 8]
 - Browser [Chrome]
 - Version [71.0.3578.98]

**Smartphone (please complete the following information):**
 - Device: []
 - OS: []
 - Browser []
 - Version []

**Environment/Server:**
<pre><code>
- [X] Production
- [ ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: 30 January 2019

**Comment by edwinmp** [comment]
@jamesharle see below

![image](https://user-images.githubusercontent.com/5672438/51116149-5756ca00-181b-11e9-808f-cea5c37761c3.png)

**Comment by jamesharle** [comment]
Perfect :)
