### ISSUE TITLE
Colour change country profiles 'how is spending allocated?' graphic

### ISSUE THREAD

**Issue by jamesharle** [devinit/datahub#478]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
The 'how is spending allocated?' graphic, located under the Government Finance tab of Country Profiles, is off-brand. Specifically, we need the green #109e68 changed to the blue #88bae5. These changes will apply to the key as well as the donut itself.
**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to any country profile
2. Click on the 'government finance' tab.

**Expected Behaviour**
We'd like this to be on brand.

**Screenshots/GIF**
![image](https://user-images.githubusercontent.com/43270042/50282356-6f207580-044a-11e9-8681-5fee3bb66956.png)

**Desktop (please complete the following information):**
 - OS: [windows 8]
 - Browser [Chrome]
 - Version [71.0.3578.98]

**Smartphone (please complete the following information):**
 - Device: []
 - OS: []
 - Browser []
 - Version []

**Environment/Server:**
<pre><code>
- [X] Production
- [ ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: 30 January 2019

**Comment by edwinmp** [comment]
Hi @jamesharle ... the graphic for Uganda has more options. Do any of those need changing as well?

<img width="404" alt="screenshot 2019-01-14 at 14 59 08" src="https://user-images.githubusercontent.com/5672438/51111564-74849c00-180d-11e9-89b2-d6da2e0d23c2.png">

**Comment by jamesharle** [comment]
Thanks @edwinmp - Hmmm. Is 4 the maximum number of options that can appear here? If so, would be great to do four shades of the same base colour. If it's more than 4, don't worry about this ticket, as it would require a more complicated solution.
