### ISSUE TITLE
Colour change for country profile international resource graphics

### ISSUE THREAD

**Issue by jamesharle** [devinit/datahub#479]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
The How have resource inflows changed over time? graphic, located under the International Resources tab of Country Profiles, is off-brand. 

Specifically, in the inflows over time graphic, we'd like the red #e8443a changed to the dark green #065139; the green #109e68 changed to the light green #92cba9; and the blue #0089cc changed to the green #109e68. 

In the What's the mix of resources? graphic, we'd like 

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to any country profile
2. Click on the 'International Resources' tab.

**Expected Behaviour**
We'd like this to be on-brand

**Screenshots/GIF**
![image](https://user-images.githubusercontent.com/43270042/50283398-b2c8ae80-044d-11e9-99fc-f41466597a78.png)

**Desktop (please complete the following information):**
 - OS: [windows 8]
 - Browser [Chrome]
 - Version [71.0.3578.98]

**Smartphone (please complete the following information):**
 - Device: []
 - OS: []
 - Browser []
 - Version []

**Environment/Server:**
<pre><code>
- [X] Production
- [ ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: 30 January 2019

**Comment by edwinmp** [comment]
Hi @jamesharle ... you terminated your last sentence under "Describe the issue" halfway. Could you please complete that so I can implement it.

Also, you wanted the colour green `#109e68` changed to the light green `#92cba9`. Unfortunately, the currently colour records have `#5ab88a` as light green and `#b1d8bb` as lighter green. Do you need me to change that? (it may affect more than one area of the DDH). Go [here](https://github.com/devinit/datahub-cms/blob/master/global/colors.csv) for the full list of colours.

**Comment by jamesharle** [comment]
Thanks @edwinmp - sorry for the malformed feedback there! I believe that no change is required to the second graphic in the end - initially I had wanted to change this to different shades of the same colour, but on closer examination I believe that the number of dimensions (types of finance) used here can sometimes be more than 5, in which case it's too hard to change it.

It would be better to use the #92cba9 green, so if you wouldn't mind replacing the current green in the first instance, that'd be great. I'm not sure why Allan would have used this green, perhaps there is a reason for it - but if we notice any issues we can always switch back.

**Comment by edwinmp** [comment]
@jamesharle this is the new look. If that's alright, will deploy it.

![image](https://user-images.githubusercontent.com/5672438/51040260-0d29da80-15c8-11e9-81b6-41d78bf3d290.png)

**Comment by jamesharle** [comment]
Perfect! Thanks E :)
