### ISSUE TITLE
Add a button for downloading the data responsible for a specific map

### ISSUE THREAD

**Issue by edwinmp** [devinit/datahub#485]
**Is your feature request related to a problem? Please describe.**
I'd like there to be a more direct way to download the data responsible for what's seen on the maps, for example on the Global Picture.

**Describe the solution you'd like**
Suggestion is for a "Download the source data" button somewhere accessible, e.g. next to or below the "Share this chart" button. It should pull the data from the API in CSV format.

**Requested Delivery Date:** 31st January 2019

**Comment by edwinmp** [comment]
Also add option to select whether downloaded data should include all years or just a specific year.

**Comment by k8hughes** [comment]
@edwinmp on the global picture pages this seems to be working as intended and LGTM.

However if you check here:  http://212.111.41.68:8080/country/afghanistan on the country page when you click the download data button the page just refreshes.  Should a user be able to download the counntry data?

**Comment by edwinmp** [comment]
@k8hughes this should be fixed as well.

**Comment by k8hughes** [comment]
One last question, should we have it on this page: http://212.111.41.68:8080/unbundling-aid 

It would be nice to have the data for download her also if possible.
