### ISSUE TITLE
Determine dev needs for Datahub API

### ISSUE THREAD

**Issue by akmiller01** [devinit/datahub#487]
With most of the user needs for the API incorporated, we need to take a look at a few dev/technical needs before we go live with it.

1. Is it secure? Will it allow access to our DB in ways that could be malicious?
2. Is it robust? Will repeated use/high-traffic lead to too much strain on our server?

**Comment by edwinmp** [comment]
@akmiller01 it's also prudent to plan for future changes, some major ones that may be breaking. For that, we should version the API.

Also, I think we should standardise the response format ... something simple that simplifies things for developers e.g. { code: 200, data: [{ ... }] }

**Comment by edwinmp** [comment]
@akmiller01 For load testing:- https://loader.io looks good.

**Comment by edwinmp** [comment]
@akmiller01 done some load tests on loader.io and it seems the API can handle on average 30 client requests per sec.

**Comment by Duncan-Knox** [comment]
Does the World Bank one include all data entries (within their country/year template) which are null? From my perspective it sounds fine for our one to exclude this filter too and/or let the users decide @edwinmp. My issue around null and 0 was understanding how they were being treated and making sure we had the option of showing the latter for certain visuals on the front-end.

On this point I'd be interested to know which data download the user would end up getting, would it be the original data series straight from the warehouse or data which is tied to the front-end visual in some way (for example a download from the global picture page would have entries for all countries)?

**Comment by k8hughes** [comment]
@edwinmp is it the case  that the use is getting single indicator data depending on what indicator is currently highlighted on the global picture when they click to download the data?

**Comment by edwinmp** [comment]
@k8hughes yes, the downloads on the maps are per indicator.
@Duncan-Knox it is pulled straight from the warehouse but only as it relates to a particular visual. As far as I can tell, there's rarely any joins, so we're pulling the original data series. For example, on the Global Picture and Spotlights, each indicator corresponds to a specific warehouse table.

**Comment by akmiller01** [comment]
@edwinmp the only join performed by the API is joining entity names to entity ids!

**Comment by akmiller01** [comment]
Testing loads of the CSV exporter now @edwinmp , I think it's doing much better now:

![image](https://user-images.githubusercontent.com/2836840/51617777-f43ff400-1efa-11e9-88bc-58214bc0576b.png)

**Comment by edwinmp** [comment]
@akmiller01 I think it's more than adequate. We'll have to keep track of it as the data grows but for now this should be fine.
