### ISSUE TITLE
Bug on unbundling aid

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/datahub#488]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[] Bug report 
[X] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Ordering of categories is inflexible when the user clicks through the treemap. Edit: unsure if related to this this issue, the category being moved by the user is the one that ends up showing first, I believe it was set-up to always show the category furthest left first, allowing others to be re-organised.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'Unbundling and'
2. Reorganise categories at top.
3. Click through on the interactive treemap.
4. See error - ordering does not change to reflect the categories.

**Expected Behaviour**
It should be possible to click through the categories in the order they are shown at the top. 

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.
Ordering should 

This GIF demonstrates the click through always follows the original ordering (to, from, sectors, forms, channels) of the categories and is not flexible. 
![unbundling aid gif](https://user-images.githubusercontent.com/13347058/51120864-f4126b00-180d-11e9-8f3b-8cd599ee8b35.gif)

In this second example. The click through should go from donor 'from' to recipient 'to' . However it jumps straight to sector.
![unbundling aid gif 2](https://user-images.githubusercontent.com/13347058/51123573-45255d80-1814-11e9-966f-dcc2a8d6a3df.gif)

**Environment/Server:**
<pre><code>
- [X] Production
- [ ] Staging
- [ ] Test
- [ ] Development
</code></pre>

**Additional Context**
The first category on the left should be the one that shows on the first layer. The categories going right are the ones which show in-order as the treemap is clicked through. Have marked as a regression. Unsure exactly when this issue came into play.

Requested Delivery Date: when feasible given workload - to diagnose by end of next sprint if possible?

**Comment by edwinmp** [comment]
Hi @Duncan-Knox ... just deployed the fix for this on staging. Please test.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp thanks for the update. The fix looks excellent. I've tested it out and it runs very smoothly.
