### ISSUE TITLE
A banner to notify users data is out of date

### ISSUE THREAD

**Issue by k8hughes** [devinit/datahub#498]
**Is your feature request related to a problem? Please describe.**
The DDH is now out of date in several places.  We need to let users know we know, so they don't think it is a DI error.

**Describe the solution you'd like**
A banner that is on all pages that says:
The Development Data Hub is currently not displaying the most up to date data as it is soon to undergo redevelopment, if you have any data related questions please email info@devinit.org
  
**Describe alternatives you've considered**

**Additional context**

**Requested Delivery Date:** dd/MMM/YYYY
Eary next week

**Comment by k8hughes** [comment]
Slight change to the copy: 
The Development Data Hub is not currently displaying the most up-to-date data, as it is soon to undergo redevelopment. If you have any data-related questions please email info@devinit.org

**Comment by edwinmp** [comment]
![image](https://user-images.githubusercontent.com/5672438/59209177-5bf99180-8bb3-11e9-8bfd-31ad61521f9e.png)

@k8hughes Will that do?

**Comment by k8hughes** [comment]
With it all in white it doesn't stand out, is there a way of making it more prominent?

**Comment by edwinmp** [comment]
Sure ... we could either go for a bigger font-size, or choose a brighter colour that'd stand out... I'm open to suggestions :)

![image](https://user-images.githubusercontent.com/5672438/59257214-2fd72280-8c3e-11e9-921e-cbd893655e76.png)

**Comment by k8hughes** [comment]
For me it is the white on white that is the issue.  Can we try giving it a border so it is clear an banner not just part of the page?

**Comment by k8hughes** [comment]
I just showed Rohini and she suggestion was to try changing the background of the banner to one fo the other very light reds in the brand colours so the background is more visable.

**Comment by edwinmp** [comment]
![image](https://user-images.githubusercontent.com/5672438/59258627-feac2180-8c40-11e9-8c27-daac6f82d954.png)

![image](https://user-images.githubusercontent.com/5672438/59258683-184d6900-8c41-11e9-9249-e784b9e24710.png)

**Comment by samuele-mattiuzzo** [comment]
- Yellow is the color you want to go with for such a warning
- The warning div should be detached from the top menu and possibly not span 100% of the width
- Text inside it should be bolder (like the menu items) and slightly bigger

Check out the examples in this page here https://isabelcastillo.com/error-info-messages-css: the warning box is perfect (although in our case text should be centered and bold)

The icons add an extra nice touch to it all, I would use the `i` icon since we're informing people about something.

Also, a nice `x` in the top-right corner to hide the banner would be nice, as it is just a fyi temporary piece of information (somebody that stays on the website for 1-2 hours doesn't need reminding every page)

**Comment by edwinmp** [comment]
Initial one was a warning alert ... maybe its shade of yellow was just too light. Problem is, there's a fondness for DI brand colours that tends to move us away from conventional choices. Yup, will make it closable.

Alright... version 3.0 coming up.

**Comment by edwinmp** [comment]
@k8hughes http://212.111.41.68:8080/

**Comment by edwinmp** [comment]
Found some DI brand colours for the DDH in the datahub-cms. That shade of yellow is brand and also adheres to convention.

@samuele-mattiuzzo opted for a full width version. More uniform across multiple pages.

**Comment by k8hughes** [comment]
This is good as it looks much more like a warning, sorry to have another change, but now the text feels too big.  Once we can reduce the text size a bit it should be good.

**Comment by samuele-mattiuzzo** [comment]
> @samuele-mattiuzzo opted for a full width version. More uniform across multiple pages.

I would still suggest to have it adapt when going for mobile (in which case 100% width is fine, but for desktop keep it as a non full width bar)

also, I'd still say to follow the color palette of the link I shared: black text on yellow bg doesn't stand out as a warning enough

**Comment by edwinmp** [comment]
@samuele-mattiuzzo better? http://212.111.41.68:8080/

**Comment by samuele-mattiuzzo** [comment]
Yes @edwinmp much better! Maybe work a bit on the weight of the bold font, but looks great!

Also, take a look at the responsive style of the menu (if it's already being worked on or you prefer me to raise this in a separate issue let me know)

![Screenshot 2019-06-13 at 11 58 42 am](https://user-images.githubusercontent.com/1381563/59427516-bb81b800-8dd2-11e9-91fd-5399424311d9.png)

**Comment by k8hughes** [comment]
@samuele-mattiuzzo can you be the one to LGTM this when it is ready for release?  :awthanks:

**Comment by samuele-mattiuzzo** [comment]
@edwinmp have you made any other changes on this?

**Comment by edwinmp** [comment]
@samuele-mattiuzzo fixed the responsive style of the menu. Wasn't a big issues, so didn't bother opening up a new issue for it.
