### ISSUE TITLE
UI Cross checking & review with comms

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub#56]

**Comment by BeckyWillmoth** [comment]
Discussed with Bex, can you add her to this repository and she can support to review end of this week? Thanks :)

**Comment by epicallan** [comment]
hi @RebeccaHills

We have 2 links where you will be able to check the UI comms related work of this project. These urls are bound to change with each new deployment so i will be sending you fresh urls every time we make a milestone.


1) The staging test site url which for now is: https://zeit.co/epicallan/datahub/gvbxvbhvjg
2) The sites UI component link: https://zeit.co/epicallan/storybook/ethekfpaug

You will find the components link to have more items for review than the site link at the moment.
What we do is we develop components in isolation and then include them in the site.

We are not yet done with the maps which i believe would have been a major point of interest following the color changes. Planning to have those done late this week

**Comment by RebeccaHills** [comment]
Hi @epicallan 
 
I can't seem to access the first link. Please can you let me know if there is an updated link?

Bex

**Comment by BeckyWillmoth** [comment]
@epicallan, @RebeccaHills has confirmed that she can review on 20.07.17. Can you provide links and instructions in this issue on the morning on 20.07.17? Thanks :)

**Comment by epicallan** [comment]
closed in favour of #86
