### ISSUE TITLE
Rule around when to show year in map tool tips

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub#89]
Some maps on the data hub have a year in their tooltips while others don't yet they could also have. Can we have a clear rule on when to show year and when not to for consistence.

![screen shot 2017-07-31 at 11 08 02](https://user-images.githubusercontent.com/6281527/28768504-8f56ea0e-75e0-11e7-9d29-7ffdd26df495.png)
![screen shot 2017-07-31 at 11 07 34](https://user-images.githubusercontent.com/6281527/28768505-8ff4fd16-75e0-11e7-83db-897763e7316e.png)

**Comment by RebeccaHills** [comment]
Hi @epicallan 

My thoughts are that they should all have years - unless there is a specific reason that I don't know about. @kb4777 might be able to confirm we can add years to all?

Thanks

**Comment by kb4777** [comment]
Good spot @epicallan , thanks for that. Given the year slider at the bottom would say the same information, I don't think there can be a reason not to put the year in all instances. So please do add years to all.

Thank you!

**Comment by epicallan** [comment]
@RebeccaHills  & @kb4777 Thanks for the feedback will add a year to all where applicable.
