### ISSUE TITLE
Change color scheme for p20 regional & survey maps to match new color gradient

### ISSUE THREAD

**Issue by epicallan** [devinit/datahub#90]
To be done once branding issues are cleared.

Branding issues: #86

**Comment by epicallan** [comment]
gradient

mid: #e8443a
low: #fbd7cb
high: #8f1b13

**Comment by akmiller01** [comment]
https://github.com/devinit/di-tileserver/commit/24def3b9f45b02c2c525480d0ddb9489b7765857
