### ISSUE TITLE
Whole site checks

### ISSUE THREAD

**Issue by kb4777** [devinit/datahub#92]

**Comment by kb4777** [comment]
- [ ]  The last two words at the very bottom of the page – ‘privacy policy’ – appear in grey, where they used to be white. There should also be a space between 'our' and 'policy'
- [ ]  In the short paragraph at the top of the page, the last sentence 'Read more about the data hub' should be red hyperlinked and take you down the page to below the map.
- [ ]  In the links at the bottom of the page, under 'Newsletter' heading, the words 'Development Initiatives newsletter' should be hyperlinked (in white, with a red hover). Similarly 'Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license' should also be a link.
- [ ]  At the bottom of the page, under the 'Sections' and 'Quick Links' headings, all the links point towards the DI blog. Also, the blog page only loads about half the time. The rest of the time it say 'Oops! That page can’t be found.' (This oops message also happens on the live data hub.)
- [ ]  The four social media icons at bottom of the page all link to DI's twitter account.

**Comment by epicallan** [comment]
- [ ] browser cache issue that requires one to refresh the page.
